import '../training_library_models.dart';

final List<TrainingSessionTemplate> enduranceSessionsBlock1 = [
  TrainingSessionTemplate(
    id: 'endurance_024',
    number: 24,
    title: '10 x 400 m técnico + 600 m suave',
    category: TrainingLibraryCategory.endurance,
    modality: TrainingLibraryModality.endurance,
    intensity: TrainingSessionIntensity.moderate,
    objective:
        'Desarrollar resistencia técnica manteniendo calidad de postura y empuje.',
    type: 'Resistencia técnica en patines',
    warmup: [
      'Rodaje suave 12 minutos.',
      'Movilidad dinámica 5 minutos.',
      '3 progresivos de 100 m.',
    ],
    mainSet: [
      '10 x 400 m técnico.',
      'Recuperación 200 m suave entre repeticiones.',
      'Finalizar con 600 m suave.',
    ],
    complementary: [
      'Movilidad de cadera 5 minutos.',
      'Respiración 90/90 3 minutos.',
    ],
    technicalCues: [
      'Postura estable.',
      'Empuje lateral limpio.',
      'No perder técnica por fatiga.',
    ],
    commonErrors: [
      'Convertirlo en lactato.',
      'Subir demasiado la intensidad.',
      'Acortar empuje.',
    ],
    cutCriteria: [
      'Pérdida técnica repetida.',
      'Pulso excesivo para el objetivo.',
      'Dolor lumbar o de rodilla.',
    ],
    coachNotes:
        'Sesión base para fondistas, útil también en mixtos si se controla intensidad.',
    skatingSession: true,
    gymSession: false,
    cyclingSession: false,
    recoverySession: false,
    neuralFocused: false,
    metabolicFocused: true,
    reactiveFocused: false,
    technicalFocused: true,
    taperCompatible: false,
    tags: ['endurance', 'technical', '400m', 'aerobic', 'skating'],
  ),
  TrainingSessionTemplate(
    id: 'endurance_025',
    number: 25,
    title: 'Cambios 200 fuerte / 400 suave',
    category: TrainingLibraryCategory.tempo,
    modality: TrainingLibraryModality.endurance,
    intensity: TrainingSessionIntensity.high,
    objective:
        'Mejorar cambios de ritmo y recuperación activa entre esfuerzos.',
    type: 'Fartlek específico en patines',
    warmup: [
      'Rodaje suave 15 minutos.',
      'Movilidad dinámica.',
      '4 progresivos de 80 m.',
    ],
    mainSet: [
      '8 a 12 bloques: 200 m fuerte + 400 m suave.',
      'Mantener técnica en el cambio de ritmo.',
      'Recuperación siempre patinando.',
    ],
    complementary: ['Rodaje suave 8 minutos.', 'Movilidad de psoas y tobillo.'],
    technicalCues: [
      'Acelerar sin romper postura.',
      'Recuperar respiración en los 400 m.',
      'Mantener empuje lateral.',
    ],
    commonErrors: [
      'Hacer los 200 m como sprint máximo.',
      'No recuperar en los 400 m.',
      'Desordenar técnica.',
    ],
    cutCriteria: [
      'Caída marcada de velocidad.',
      'Lactato excesivo temprano.',
      'Pérdida de control en curvas.',
    ],
    coachNotes:
        'Muy útil para puntos, ataques y cambios de ritmo. Vigilar carga metabólica.',
    skatingSession: true,
    gymSession: false,
    cyclingSession: false,
    recoverySession: false,
    neuralFocused: false,
    metabolicFocused: true,
    reactiveFocused: false,
    technicalFocused: true,
    taperCompatible: false,
    tags: ['tempo', 'endurance', 'surges', 'points-race', 'metabolic'],
  ),
  TrainingSessionTemplate(
    id: 'endurance_033',
    number: 33,
    title: 'Rodaje técnico 45 minutos',
    category: TrainingLibraryCategory.endurance,
    modality: TrainingLibraryModality.universal,
    intensity: TrainingSessionIntensity.low,
    objective: 'Construir base aeróbica suave con énfasis técnico.',
    type: 'Rodaje técnico',
    warmup: ['Movilidad general 5 minutos.', 'Rodaje progresivo 10 minutos.'],
    mainSet: [
      'Rodaje continuo 45 minutos en Z2 baja.',
      'Cada 10 minutos incluir 2 minutos de foco técnico.',
      'Mantener sensación controlada.',
    ],
    complementary: [
      'Movilidad global 8 minutos.',
      'Respiración nasal 3 minutos.',
    ],
    technicalCues: [
      'Patín silencioso.',
      'Postura cómoda.',
      'Empuje amplio sin tensión.',
    ],
    commonErrors: [
      'Subir intensidad.',
      'Perseguir velocidad media.',
      'Perder técnica por volumen.',
    ],
    cutCriteria: [
      'Pulso fuera de zona.',
      'Dolor articular.',
      'Fatiga creciente no esperada.',
    ],
    coachNotes:
        'Compatible con base general. En velocistas usar con volumen controlado.',
    skatingSession: true,
    gymSession: false,
    cyclingSession: false,
    recoverySession: false,
    neuralFocused: false,
    metabolicFocused: false,
    reactiveFocused: false,
    technicalFocused: true,
    taperCompatible: true,
    tags: ['endurance', 'technical', 'z2', 'aerobic-base'],
  ),
  TrainingSessionTemplate(
    id: 'endurance_034',
    number: 34,
    title: 'Fondo largo con aceleraciones',
    category: TrainingLibraryCategory.endurance,
    modality: TrainingLibraryModality.endurance,
    intensity: TrainingSessionIntensity.moderate,
    objective:
        'Desarrollar resistencia prolongada incorporando aceleraciones controladas.',
    type: 'Fondo específico',
    warmup: [
      'Rodaje suave 15 minutos.',
      'Movilidad dinámica.',
      '3 progresivos cortos.',
    ],
    mainSet: [
      '60 a 90 minutos de fondo en Z2.',
      'Cada 12 minutos realizar aceleración de 15 segundos.',
      'Volver inmediatamente a ritmo aeróbico.',
    ],
    complementary: [
      'Rodaje muy suave 8 minutos.',
      'Movilidad de cadera e isquios.',
    ],
    technicalCues: [
      'Aceleración limpia, no máxima.',
      'Recuperar postura después de cada cambio.',
      'Mantener hidratación.',
    ],
    commonErrors: [
      'Convertir aceleraciones en sprints máximos.',
      'No volver a Z2.',
      'Acumular fatiga técnica.',
    ],
    cutCriteria: [
      'Pérdida técnica marcada.',
      'Pulso alto sostenido.',
      'Dolor distal o lumbar.',
    ],
    coachNotes:
        'Base importante para fondistas; útil para remates sin romper trabajo aeróbico.',
    skatingSession: true,
    gymSession: false,
    cyclingSession: false,
    recoverySession: false,
    neuralFocused: false,
    metabolicFocused: true,
    reactiveFocused: false,
    technicalFocused: true,
    taperCompatible: false,
    tags: ['endurance', 'long-ride', 'accelerations', 'aerobic'],
  ),
  TrainingSessionTemplate(
    id: 'endurance_035',
    number: 35,
    title: 'Tempo 3 x 10 minutos',
    category: TrainingLibraryCategory.tempo,
    modality: TrainingLibraryModality.endurance,
    intensity: TrainingSessionIntensity.high,
    objective: 'Mejorar ritmo sostenido y tolerancia a intensidad submáxima.',
    type: 'Tempo en patines',
    warmup: [
      'Rodaje suave 15 minutos.',
      '4 progresivos de 100 m.',
      'Movilidad dinámica.',
    ],
    mainSet: [
      '3 x 10 minutos tempo.',
      'Recuperación 4 minutos suave.',
      'Mantener técnica estable.',
    ],
    complementary: [
      'Rodaje suave 10 minutos.',
      'Movilidad de cadera y respiración.',
    ],
    technicalCues: [
      'Ritmo fuerte pero controlado.',
      'No salir demasiado rápido.',
      'Postura baja eficiente.',
    ],
    commonErrors: [
      'Pasarse a intensidad lactácida.',
      'Caer de ritmo en el segundo bloque.',
      'Perder empuje lateral.',
    ],
    cutCriteria: [
      'Caída marcada de ritmo.',
      'Técnica degradada.',
      'Readiness bajo o fatiga excesiva.',
    ],
    coachNotes:
        'Carga metabólica alta. Evitar junto a lactato fuerte en días consecutivos.',
    skatingSession: true,
    gymSession: false,
    cyclingSession: false,
    recoverySession: false,
    neuralFocused: false,
    metabolicFocused: true,
    reactiveFocused: false,
    technicalFocused: true,
    taperCompatible: false,
    tags: ['tempo', 'threshold', 'endurance', 'metabolic'],
  ),
  TrainingSessionTemplate(
    id: 'endurance_036',
    number: 36,
    title: 'Tempo en grupo con relevos',
    category: TrainingLibraryCategory.tempo,
    modality: TrainingLibraryModality.endurance,
    intensity: TrainingSessionIntensity.high,
    objective:
        'Desarrollar ritmo de grupo, relevos y eficiencia táctica en esfuerzo sostenido.',
    type: 'Tempo táctico en grupo',
    warmup: [
      'Rodaje grupal suave 15 minutos.',
      'Práctica de relevos suaves 5 minutos.',
    ],
    mainSet: [
      '3 bloques de 8 a 12 minutos tempo en grupo.',
      'Relevos cada 1 vuelta o según pista.',
      'Recuperación 5 minutos suave entre bloques.',
    ],
    complementary: [
      'Rodaje suave 8 minutos.',
      'Movilidad global post-entreno.',
    ],
    technicalCues: [
      'Relevo limpio.',
      'No acelerar al pasar.',
      'Mantener distancia segura.',
    ],
    commonErrors: [
      'Romper ritmo en cada relevo.',
      'Ir demasiado fuerte al frente.',
      'Desordenar fila.',
    ],
    cutCriteria: [
      'Riesgo por grupo desordenado.',
      'Pérdida técnica.',
      'Fatiga excesiva.',
    ],
    coachNotes:
        'Clave para fondistas y mixtos. Trabaja físico y táctica de carrera.',
    skatingSession: true,
    gymSession: false,
    cyclingSession: false,
    recoverySession: false,
    neuralFocused: false,
    metabolicFocused: true,
    reactiveFocused: false,
    technicalFocused: true,
    taperCompatible: false,
    tags: ['tempo', 'group', 'drafting', 'relay', 'tactical'],
  ),
  TrainingSessionTemplate(
    id: 'endurance_120',
    number: 120,
    title: 'Relevos cada vuelta',
    category: TrainingLibraryCategory.tactical,
    modality: TrainingLibraryModality.endurance,
    intensity: TrainingSessionIntensity.moderate,
    objective:
        'Mejorar coordinación de relevos, lectura de grupo y eficiencia en drafting.',
    type: 'Táctico grupal',
    warmup: [
      'Rodaje suave grupal 12 minutos.',
      'Relevos técnicos suaves 5 minutos.',
    ],
    mainSet: [
      '4 bloques de 6 vueltas con relevos cada vuelta.',
      'Recuperación 4 minutos suave.',
      'Priorizar orden y seguridad.',
    ],
    complementary: [
      'Técnica de entrada y salida de relevo 5 minutos.',
      'Movilidad de cadera.',
    ],
    technicalCues: [
      'Entrar suave al relevo.',
      'Mirar antes de moverse.',
      'Mantener línea.',
    ],
    commonErrors: [
      'Acelerar al relevar.',
      'Abrirse demasiado.',
      'Cortar línea del compañero.',
    ],
    cutCriteria: [
      'Grupo inseguro.',
      'Choques o cruces peligrosos.',
      'Fatiga que altera técnica.',
    ],
    coachNotes:
        'Sesión táctica de baja a moderada carga si se controla velocidad.',
    skatingSession: true,
    gymSession: false,
    cyclingSession: false,
    recoverySession: false,
    neuralFocused: false,
    metabolicFocused: true,
    reactiveFocused: false,
    technicalFocused: true,
    taperCompatible: true,
    tags: ['tactical', 'relay', 'drafting', 'group', 'endurance'],
  ),
  TrainingSessionTemplate(
    id: 'endurance_121',
    number: 121,
    title: 'Ataque y recuperación en grupo',
    category: TrainingLibraryCategory.tactical,
    modality: TrainingLibraryModality.endurance,
    intensity: TrainingSessionIntensity.high,
    objective: 'Entrenar ataques, respuesta y recuperación dentro de grupo.',
    type: 'Táctico con cambios de ritmo',
    warmup: [
      'Rodaje suave 15 minutos.',
      '3 aceleraciones progresivas.',
      'Organización de grupo.',
    ],
    mainSet: [
      '6 a 8 ataques de 15 a 25 segundos.',
      'Recuperación dentro del grupo 3 a 4 minutos.',
      'Alternar quién ataca y quién responde.',
    ],
    complementary: [
      'Rodaje suave 10 minutos.',
      'Movilidad de aductores y cadera.',
    ],
    technicalCues: [
      'Atacar sin perder línea.',
      'Responder progresivo.',
      'Recuperar respiración en drafting.',
    ],
    commonErrors: [
      'Atacar como sprint máximo siempre.',
      'Responder tarde y desordenado.',
      'Cerrar espacios peligrosamente.',
    ],
    cutCriteria: [
      'Grupo inseguro.',
      'Técnica degradada.',
      'Fatiga metabólica excesiva.',
    ],
    coachNotes:
        'Muy específico para puntos, eliminación y ruta. Alta carga metabólica si se abusa.',
    skatingSession: true,
    gymSession: false,
    cyclingSession: false,
    recoverySession: false,
    neuralFocused: true,
    metabolicFocused: true,
    reactiveFocused: false,
    technicalFocused: true,
    taperCompatible: false,
    tags: ['tactical', 'attack', 'group', 'surges', 'metabolic'],
  ),
  TrainingSessionTemplate(
    id: 'endurance_142',
    number: 142,
    title: 'Maratón técnica 25 km',
    category: TrainingLibraryCategory.endurance,
    modality: TrainingLibraryModality.endurance,
    intensity: TrainingSessionIntensity.moderate,
    objective:
        'Desarrollar resistencia específica de ruta manteniendo eficiencia técnica.',
    type: 'Ruta / maratón técnico',
    warmup: ['Rodaje suave 10 minutos.', 'Movilidad dinámica 5 minutos.'],
    mainSet: [
      '25 km a ritmo aeróbico controlado.',
      'Cada 5 km revisar postura, drafting y empuje.',
      'Hidratación planificada.',
    ],
    complementary: [
      'Rodaje muy suave 5 minutos.',
      'Movilidad global post-entreno.',
    ],
    technicalCues: [
      'Economía de movimiento.',
      'Relajar hombros.',
      'Mantener línea eficiente.',
    ],
    commonErrors: [
      'Salir demasiado rápido.',
      'No hidratarse.',
      'Perder técnica en fatiga.',
    ],
    cutCriteria: [
      'Dolor distal.',
      'Fatiga excesiva.',
      'Condiciones inseguras de ruta.',
    ],
    coachNotes:
        'Sesión para fondistas de ruta. No usar cerca de competencia si genera fatiga residual.',
    skatingSession: true,
    gymSession: false,
    cyclingSession: false,
    recoverySession: false,
    neuralFocused: false,
    metabolicFocused: true,
    reactiveFocused: false,
    technicalFocused: true,
    taperCompatible: false,
    tags: ['endurance', 'marathon', 'road', '25km', 'aerobic'],
  ),
  TrainingSessionTemplate(
    id: 'endurance_143',
    number: 143,
    title: 'Ruta 60 min con drafting',
    category: TrainingLibraryCategory.endurance,
    modality: TrainingLibraryModality.endurance,
    intensity: TrainingSessionIntensity.moderate,
    objective: 'Mejorar resistencia de ruta y eficiencia en drafting.',
    type: 'Ruta grupal',
    warmup: ['Rodaje suave 10 minutos.', 'Relevos suaves 5 minutos.'],
    mainSet: [
      '60 minutos en ruta con drafting.',
      'Relevos controlados.',
      'Mantener Z2/Z3 baja.',
    ],
    complementary: [
      'Rodaje suave 5 minutos.',
      'Movilidad de cadera y tobillo.',
    ],
    technicalCues: [
      'Distancia segura.',
      'Relevo progresivo.',
      'No romper grupo.',
    ],
    commonErrors: [
      'Acelerar demasiado en relevos.',
      'Ir pegado sin control.',
      'No avisar obstáculos.',
    ],
    cutCriteria: [
      'Condiciones inseguras.',
      'Grupo desordenado.',
      'Pulso excesivo sostenido.',
    ],
    coachNotes:
        'Buena sesión para resistencia específica y lectura de grupo en ruta.',
    skatingSession: true,
    gymSession: false,
    cyclingSession: false,
    recoverySession: false,
    neuralFocused: false,
    metabolicFocused: true,
    reactiveFocused: false,
    technicalFocused: true,
    taperCompatible: false,
    tags: ['endurance', 'road', 'drafting', 'group', 'aerobic'],
  ),
  TrainingSessionTemplate(
    id: 'endurance_159',
    number: 159,
    title: '5 km técnico progresivo',
    category: TrainingLibraryCategory.endurance,
    modality: TrainingLibraryModality.mixed,
    intensity: TrainingSessionIntensity.moderate,
    objective: 'Trabajar progresión de ritmo sin perder eficiencia técnica.',
    type: 'Progresivo técnico',
    warmup: [
      'Rodaje suave 12 minutos.',
      'Movilidad dinámica.',
      '3 progresivos de 80 m.',
    ],
    mainSet: [
      '5 km progresivos.',
      'Primer 2 km suave, siguientes 2 km moderado, último 1 km fuerte controlado.',
      'Mantener técnica en el cierre.',
    ],
    complementary: ['Rodaje suave 8 minutos.', 'Movilidad global 5 minutos.'],
    technicalCues: [
      'Subir ritmo gradualmente.',
      'No sprintar al final.',
      'Conservar empuje lateral.',
    ],
    commonErrors: [
      'Salir rápido.',
      'Convertir último km en lactato máximo.',
      'Perder postura.',
    ],
    cutCriteria: [
      'Pérdida técnica.',
      'Dolor lumbar.',
      'Sensación de fatiga excesiva.',
    ],
    coachNotes:
        '�stil para mixtos y fondistas; buen puente entre base y intensidad controlada.',
    skatingSession: true,
    gymSession: false,
    cyclingSession: false,
    recoverySession: false,
    neuralFocused: false,
    metabolicFocused: true,
    reactiveFocused: false,
    technicalFocused: true,
    taperCompatible: false,
    tags: ['endurance', 'progressive', '5km', 'technical'],
  ),
  TrainingSessionTemplate(
    id: 'endurance_160',
    number: 160,
    title: '12 vueltas con metas volantes',
    category: TrainingLibraryCategory.tactical,
    modality: TrainingLibraryModality.endurance,
    intensity: TrainingSessionIntensity.high,
    objective:
        'Simular esfuerzos de carrera con metas volantes y recuperación en grupo.',
    type: 'Táctico específico puntos',
    warmup: [
      'Rodaje suave 15 minutos.',
      '3 aceleraciones progresivas.',
      'Organizar grupo y reglas.',
    ],
    mainSet: [
      '12 vueltas continuas.',
      'Meta volante cada 3 vueltas.',
      'Después de cada meta, recuperar dentro del grupo.',
    ],
    complementary: [
      'Rodaje suave 10 minutos.',
      'Movilidad de aductores, psoas y tobillo.',
    ],
    technicalCues: [
      'Ubicarse antes de la meta.',
      'Acelerar con timing.',
      'Recuperar en drafting.',
    ],
    commonErrors: [
      'Arrancar demasiado tarde.',
      'Gastar energía sin posición.',
      'Cerrar líneas peligrosas.',
    ],
    cutCriteria: [
      'Grupo inseguro.',
      'Pérdida técnica por fatiga.',
      'Exceso de lactato.',
    ],
    coachNotes:
        'Muy específico para carreras por puntos. Carga metabólica alta, no repetir demasiado seguido.',
    skatingSession: true,
    gymSession: false,
    cyclingSession: false,
    recoverySession: false,
    neuralFocused: true,
    metabolicFocused: true,
    reactiveFocused: false,
    technicalFocused: true,
    taperCompatible: false,
    tags: [
      'tactical',
      'points-race',
      'intermediate-sprint',
      'group',
      'metabolic',
    ],
  ),
];


