import '../training_library_models.dart';

final List<TrainingSessionTemplate> techniqueSessionsBlock1 = [
  TrainingSessionTemplate(
    id: 'technique_006',
    number: 6,
    title: 'Posición básica sostenida',
    category: TrainingLibraryCategory.technical,
    modality: TrainingLibraryModality.universal,
    intensity: TrainingSessionIntensity.low,
    objective: 'Mejorar postura baja, estabilidad lumbar y control de cadera.',
    type: 'Técnica postural / fuerza isométrica específica',
    warmup: [
      'Movilidad de cadera.',
      'Activación de glúteo medio.',
      '5 minutos rodaje suave.',
    ],
    mainSet: [
      '6 vueltas en posición básica.',
      '1 vuelta trabajo / 1 vuelta recuperación.',
      'Mantener tronco bajo y cadera estable.',
    ],
    complementary: ['3 x 30 seg posición baja sin patines.'],
    technicalCues: [
      'Cadera atrás.',
      'Espalda larga.',
      'Rodillas flexionadas.',
      'Peso sobre el centro del patín.',
    ],
    commonErrors: [
      'Redondear la espalda.',
      'Subir la cadera.',
      'Bloquear rodillas.',
      'Llevar peso a los talones.',
    ],
    cutCriteria: [
      'Dolor lumbar.',
      'Pérdida total de postura.',
      'Temblor excesivo.',
    ],
    coachNotes: 'Base para todos los ejercicios técnicos.',
    skatingSession: true,
    gymSession: false,
    cyclingSession: false,
    recoverySession: false,
    neuralFocused: false,
    metabolicFocused: false,
    reactiveFocused: false,
    technicalFocused: true,
    taperCompatible: true,
    tags: ['tecnica', 'posicion', 'postura baja', 'base'],
  ),

  TrainingSessionTemplate(
    id: 'technique_007',
    number: 7,
    title: 'Rodilla-talón en posición',
    category: TrainingLibraryCategory.technical,
    modality: TrainingLibraryModality.universal,
    intensity: TrainingSessionIntensity.low,
    objective:
        'Mejorar recuperación de pierna, flexión de cadera y control del psoas.',
    type: 'Técnica de recuperación',
    warmup: [
      'Movilidad de cadera.',
      'Activación de flexores de cadera.',
      '5 minutos patinaje suave.',
    ],
    mainSet: [
      '6 vueltas.',
      '1 vuelta trabajo / 1 vuelta recuperación.',
      'Llevar rodilla adelante y talón cerca, sin subir el tronco.',
    ],
    complementary: ['3 x 12 flexiones de cadera por pierna sin patines.'],
    technicalCues: [
      'Rodilla adelante.',
      'Talón debajo.',
      'Cadera quieta.',
      'No levantes el cuerpo.',
    ],
    commonErrors: [
      'Subir demasiado la rodilla.',
      'Rotar la pelvis.',
      'Perder equilibrio.',
      'Recuperar lejos del cuerpo.',
    ],
    cutCriteria: [
      'Se pierde estabilidad.',
      'Dolor en flexor de cadera.',
      'Compensación lumbar.',
    ],
    coachNotes: 'Muy útil para frecuencia y aceleración.',
    skatingSession: true,
    gymSession: false,
    cyclingSession: false,
    recoverySession: false,
    neuralFocused: false,
    metabolicFocused: false,
    reactiveFocused: false,
    technicalFocused: true,
    taperCompatible: true,
    tags: ['tecnica', 'recuperacion', 'rodilla talon', 'frecuencia'],
  ),

  TrainingSessionTemplate(
    id: 'technique_008',
    number: 8,
    title: 'Sostenido de curva pierna derecha',
    category: TrainingLibraryCategory.technical,
    modality: TrainingLibraryModality.universal,
    intensity: TrainingSessionIntensity.low,
    objective:
        'Mejorar estabilidad unilateral, control del filo y posición en curva.',
    type: 'Técnica de curva / equilibrio específico',
    warmup: [
      'Rodaje suave.',
      '3 vueltas técnica de curva.',
      'Movilidad de tobillo y cadera.',
    ],
    mainSet: [
      '6 vueltas.',
      'Trabajar curva sosteniendo pierna derecha.',
      'Recta técnica suave.',
    ],
    complementary: ['3 x 20 seg equilibrio unilateral.'],
    technicalCues: [
      'Cadera adentro.',
      'Rodilla alineada.',
      'Presiona el filo.',
      'No colapses el tronco.',
    ],
    commonErrors: [
      'Abrirse en la curva.',
      'Perder inclinación.',
      'Apoyar pesado.',
      'Mirar hacia abajo.',
    ],
    cutCriteria: [
      'El patinador pierde trayectoria.',
      'Hay dolor de rodilla.',
      'Se cae la estabilidad.',
    ],
    coachNotes: 'Debe hacerse lento antes de hacerlo rápido.',
    skatingSession: true,
    gymSession: false,
    cyclingSession: false,
    recoverySession: false,
    neuralFocused: false,
    metabolicFocused: false,
    reactiveFocused: false,
    technicalFocused: true,
    taperCompatible: true,
    tags: ['tecnica', 'curva', 'pierna derecha', 'equilibrio'],
  ),

  TrainingSessionTemplate(
    id: 'technique_009',
    number: 9,
    title: 'Sostenido de curva pierna izquierda',
    category: TrainingLibraryCategory.technical,
    modality: TrainingLibraryModality.universal,
    intensity: TrainingSessionIntensity.low,
    objective: 'Mejorar apoyo interno y control específico de curva.',
    type: 'Técnica unilateral',
    warmup: [
      '5 minutos suave.',
      '3 curvas progresivas.',
      'Activación de glúteo medio.',
    ],
    mainSet: [
      '6 vueltas.',
      'Curva sosteniendo pierna izquierda.',
      'Recta técnica.',
    ],
    complementary: ['2 x 8 empujes laterales por pierna.'],
    technicalCues: [
      'Cadera baja.',
      'Empuja desde el suelo.',
      'Controla el tobillo.',
      'Tronco acompaña la curva.',
    ],
    commonErrors: [
      'Perder filo.',
      'Subir el tronco.',
      'Apoyar tarde.',
      'No controlar la pelvis.',
    ],
    cutCriteria: [
      'Falla el equilibrio.',
      'Aparece dolor de tobillo.',
      'Se rompe la línea técnica.',
    ],
    coachNotes: 'Clave para patinadores que se abren en curva.',
    skatingSession: true,
    gymSession: false,
    cyclingSession: false,
    recoverySession: false,
    neuralFocused: false,
    metabolicFocused: false,
    reactiveFocused: false,
    technicalFocused: true,
    taperCompatible: true,
    tags: ['tecnica', 'curva', 'pierna izquierda', 'equilibrio'],
  ),

  TrainingSessionTemplate(
    id: 'technique_010',
    number: 10,
    title: 'Traspiés sin levantar los pies',
    category: TrainingLibraryCategory.technical,
    modality: TrainingLibraryModality.universal,
    intensity: TrainingSessionIntensity.low,
    objective:
        'Mejorar coordinación de curva, transferencia de peso y control del cruce.',
    type: 'Técnica de curva',
    warmup: [
      'Rodaje técnico.',
      'Movilidad de cadera.',
      '3 vueltas con curvas suaves.',
    ],
    mainSet: [
      '6 vueltas.',
      'En curva: traspiés sin levantar los pies.',
      'En recta: patinar técnico.',
    ],
    complementary: ['Slalom borde externo 3 vueltas.'],
    technicalCues: [
      'Cruza suave.',
      'No saltes.',
      'Transfiere peso.',
      'Cadera guía el movimiento.',
    ],
    commonErrors: [
      'Levantar demasiado el pie.',
      'Cruzar sin empuje.',
      'Perder ritmo.',
      'Rotar hombros.',
    ],
    cutCriteria: [
      'Se pierde fluidez.',
      'El patinador tropieza.',
      'Aparece rigidez.',
    ],
    coachNotes: 'Ejercicio perfecto para enseñar curva sin ansiedad.',
    skatingSession: true,
    gymSession: false,
    cyclingSession: false,
    recoverySession: false,
    neuralFocused: false,
    metabolicFocused: false,
    reactiveFocused: false,
    technicalFocused: true,
    taperCompatible: true,
    tags: ['tecnica', 'curva', 'traspies', 'coordinacion'],
  ),

  TrainingSessionTemplate(
    id: 'technique_011',
    number: 11,
    title: 'Empujes laterales una pierna',
    category: TrainingLibraryCategory.technical,
    modality: TrainingLibraryModality.universal,
    intensity: TrainingSessionIntensity.moderate,
    objective:
        'Mejorar transferencia lateral, estabilidad y fuerza específica del empuje.',
    type: 'Técnica + fuerza específica',
    warmup: [
      'Activación glúteo medio.',
      'Movilidad cadera.',
      '5 minutos patinaje suave.',
    ],
    mainSet: [
      '6 vueltas.',
      'Recta 1: empuje lateral pierna derecha.',
      'Recta 2: empuje lateral pierna izquierda.',
      'Curvas suaves.',
    ],
    complementary: ['3 x 10 zancadas laterales sin patines.'],
    technicalCues: [
      'Empuja lateral.',
      'No empujes hacia atrás solamente.',
      'Cadera estable.',
      'Termina el empuje.',
    ],
    commonErrors: [
      'Empuje corto.',
      'Rodilla hacia adentro.',
      'Cadera sube.',
      'Apoyo inestable.',
    ],
    cutCriteria: [
      'Pierde alineación.',
      'Dolor aductor o rodilla.',
      'No controla el apoyo.',
    ],
    coachNotes: 'Muy importante para velocistas y fondistas.',
    skatingSession: true,
    gymSession: false,
    cyclingSession: false,
    recoverySession: false,
    neuralFocused: false,
    metabolicFocused: false,
    reactiveFocused: false,
    technicalFocused: true,
    taperCompatible: true,
    tags: ['tecnica', 'empuje lateral', 'transferencia', 'unilateral'],
  ),

  TrainingSessionTemplate(
    id: 'technique_012',
    number: 12,
    title: 'Traslados de cadera',
    category: TrainingLibraryCategory.technical,
    modality: TrainingLibraryModality.universal,
    intensity: TrainingSessionIntensity.low,
    objective: 'Mejorar cambio de peso y control del centro de masa.',
    type: 'Técnica de transferencia',
    warmup: [
      '5 minutos rodaje.',
      'Movilidad de cadera.',
      '2 vueltas slalom suave.',
    ],
    mainSet: [
      '6 vueltas.',
      'Trasladar cadera derecha e izquierda con control.',
      'Mantener posición baja.',
    ],
    complementary: ['2 x 12 traslados sin patines frente a espejo.'],
    technicalCues: [
      'La cadera manda.',
      'El hombro no se cruza.',
      'Peso sobre apoyo.',
      'Centro bajo.',
    ],
    commonErrors: [
      'Mover solo hombros.',
      'No transferir peso.',
      'Subir y bajar demasiado.',
      'Patinar plano.',
    ],
    cutCriteria: [
      'No hay control de cadera.',
      'Pérdida de equilibrio.',
      'Fatiga técnica.',
    ],
    coachNotes: 'Ejercicio fundamental para eficiencia.',
    skatingSession: true,
    gymSession: false,
    cyclingSession: false,
    recoverySession: false,
    neuralFocused: false,
    metabolicFocused: false,
    reactiveFocused: false,
    technicalFocused: true,
    taperCompatible: true,
    tags: ['tecnica', 'cadera', 'transferencia', 'eficiencia'],
  ),
];


