import '../training_library_models.dart';

final List<TrainingSessionTemplate> cooldownSessionsBlock1 = [
  TrainingSessionTemplate(
    id: 'cooldown_speed_001',
    number: 301,
    title: 'Cooldown post velocidad',
    category: TrainingLibraryCategory.recovery,
    modality: TrainingLibraryModality.universal,
    intensity: TrainingSessionIntensity.recovery,
    objective:
        'Bajar activación neural y reducir tensión después de velocidad máxima.',
    type: 'Cooldown velocidad',
    warmup: ['Rodaje muy suave 5 minutos.'],
    mainSet: [
      'Rodaje suave adicional 5 a 8 minutos.',
      'Movilidad de cadera y tobillo 5 minutos.',
      'Respiración nasal controlada 2 minutos.',
    ],
    complementary: [
      'Liberación suave de planta del pie.',
      'Hidratación y caminata ligera.',
    ],
    technicalCues: [
      'Reducir pulsaciones progresivamente.',
      'No detenerse de golpe.',
      'Respirar lento.',
    ],
    commonErrors: [
      'Sentarse inmediatamente.',
      'Omitir movilidad.',
      'Cerrar sesión demasiado rápido.',
    ],
    cutCriteria: [
      'Mareo.',
      'Dolor muscular creciente.',
      'Sensación de rigidez fuerte.',
    ],
    coachNotes:
        'Muy útil después de flying sprints, salidas y velocidad máxima.',
    skatingSession: true,
    gymSession: false,
    cyclingSession: false,
    recoverySession: true,
    neuralFocused: false,
    metabolicFocused: false,
    reactiveFocused: false,
    technicalFocused: false,
    taperCompatible: true,
    tags: ['cooldown', 'speed', 'neural', 'recovery'],
  ),
  TrainingSessionTemplate(
    id: 'cooldown_lactate_001',
    number: 302,
    title: 'Cooldown post lactato',
    category: TrainingLibraryCategory.recovery,
    modality: TrainingLibraryModality.universal,
    intensity: TrainingSessionIntensity.recovery,
    objective: 'Facilitar aclarado metabólico y reducir rigidez post lactato.',
    type: 'Cooldown lactato',
    warmup: ['Rodaje muy suave 5 minutos.'],
    mainSet: [
      'Rodaje Z1 de 10 a 15 minutos.',
      'Movilidad suave de cadera y columna.',
      'Respiración controlada 3 minutos.',
    ],
    complementary: ['Movilidad de psoas.', 'Movilidad torácica suave.'],
    technicalCues: [
      'Moverse relajado.',
      'Respirar profundo.',
      'No buscar intensidad.',
    ],
    commonErrors: [
      'Parar abruptamente.',
      'Estiramientos agresivos.',
      'No hidratarse.',
    ],
    cutCriteria: [
      'Mareo persistente.',
      'Dolor muscular anormal.',
      'Náusea o sensación de colapso.',
    ],
    coachNotes:
        'Importante después de 200 m, 300 m, repeated sprint y simulaciones.',
    skatingSession: true,
    gymSession: false,
    cyclingSession: false,
    recoverySession: true,
    neuralFocused: false,
    metabolicFocused: false,
    reactiveFocused: false,
    technicalFocused: false,
    taperCompatible: true,
    tags: ['cooldown', 'lactate', 'metabolic', 'recovery'],
  ),
  TrainingSessionTemplate(
    id: 'cooldown_endurance_001',
    number: 303,
    title: 'Cooldown post fondo',
    category: TrainingLibraryCategory.recovery,
    modality: TrainingLibraryModality.endurance,
    intensity: TrainingSessionIntensity.recovery,
    objective:
        'Reducir rigidez y facilitar recuperación después de volumen aeróbico.',
    type: 'Cooldown endurance',
    warmup: ['Rodaje suave 5 minutos.'],
    mainSet: [
      'Rodaje Z1 de 8 a 12 minutos.',
      'Movilidad de tobillo, cadera e isquios.',
      'Respiración nasal 2 minutos.',
    ],
    complementary: ['Caminata ligera.', 'Hidratación.'],
    technicalCues: [
      'Bajar ritmo gradualmente.',
      'Relajar hombros.',
      'No quedarse quieto inmediatamente.',
    ],
    commonErrors: [
      'Cerrar sesión abruptamente.',
      'No hacer movilidad.',
      'Seguir entrenando sin bajar pulsaciones.',
    ],
    cutCriteria: [
      'Dolor articular.',
      'Rigidez creciente.',
      'Fatiga fuera de lo esperado.',
    ],
    coachNotes: 'Especialmente útil después de ruta, maratón o tempo largo.',
    skatingSession: true,
    gymSession: false,
    cyclingSession: false,
    recoverySession: true,
    neuralFocused: false,
    metabolicFocused: false,
    reactiveFocused: false,
    technicalFocused: false,
    taperCompatible: true,
    tags: ['cooldown', 'endurance', 'aerobic', 'recovery'],
  ),
  TrainingSessionTemplate(
    id: 'cooldown_gym_001',
    number: 304,
    title: 'Cooldown post gimnasio',
    category: TrainingLibraryCategory.recovery,
    modality: TrainingLibraryModality.universal,
    intensity: TrainingSessionIntensity.recovery,
    objective:
        'Reducir tensión muscular y facilitar recuperación después de fuerza o potencia.',
    type: 'Cooldown gimnasio',
    warmup: ['Caminata o bicicleta suave 3 minutos.'],
    mainSet: [
      'Movilidad de cadera y tobillo 5 minutos.',
      'Movilidad torácica y lumbar suave.',
      'Respiración 90/90 3 minutos.',
    ],
    complementary: ['Liberación suave posterior.', 'Hidratación.'],
    technicalCues: [
      'Relajar musculatura.',
      'Respirar lento.',
      'Mover sin dolor.',
    ],
    commonErrors: [
      'Irse sin bajar carga neural.',
      'Estirar agresivamente.',
      'Ignorar rigidez lumbar o cadera.',
    ],
    cutCriteria: ['Dolor lumbar.', 'Espasmo muscular.', 'Molestia creciente.'],
    coachNotes: 'Muy útil después de fuerza máxima, unilateral o potencia.',
    skatingSession: false,
    gymSession: true,
    cyclingSession: false,
    recoverySession: true,
    neuralFocused: false,
    metabolicFocused: false,
    reactiveFocused: false,
    technicalFocused: false,
    taperCompatible: true,
    tags: ['cooldown', 'gym', 'strength', 'mobility', 'recovery'],
  ),
  TrainingSessionTemplate(
    id: 'cooldown_competition_001',
    number: 305,
    title: 'Cooldown post competencia',
    category: TrainingLibraryCategory.recovery,
    modality: TrainingLibraryModality.universal,
    intensity: TrainingSessionIntensity.recovery,
    objective:
        'Acelerar recuperación después de competencia o simulación intensa.',
    type: 'Cooldown competencia',
    warmup: ['Rodaje muy suave 5 minutos.'],
    mainSet: [
      'Rodaje Z1 10 a 15 minutos.',
      'Movilidad global suave.',
      'Respiración 90/90 4 minutos.',
    ],
    complementary: [
      'Hidratación inmediata.',
      'Cambio de ropa y reducción de estrés térmico.',
    ],
    technicalCues: [
      'Priorizar recuperación.',
      'No competir otra vez durante el cooldown.',
      'Reducir activación progresivamente.',
    ],
    commonErrors: [
      'Sentarse inmediatamente.',
      'Ignorar hidratación.',
      'Saltarse movilidad.',
    ],
    cutCriteria: ['Mareo.', 'Escalofríos.', 'Dolor muscular anormal.'],
    coachNotes:
        'Muy importante en torneos, múltiples heats o eventos de un mismo día.',
    skatingSession: true,
    gymSession: false,
    cyclingSession: false,
    recoverySession: true,
    neuralFocused: false,
    metabolicFocused: false,
    reactiveFocused: false,
    technicalFocused: false,
    taperCompatible: true,
    tags: ['cooldown', 'competition', 'recovery', 'tournament'],
  ),
];


