import '../training_library_models.dart';

final List<TrainingSessionTemplate> warmupSessionsBlock1 = [
  TrainingSessionTemplate(
    id: 'warmup_speed_001',
    number: 201,
    title: 'Calentamiento neural para velocidad',
    category: TrainingLibraryCategory.speed,
    modality: TrainingLibraryModality.universal,
    intensity: TrainingSessionIntensity.low,
    objective:
        'Preparar sistema nervioso, técnica y reactividad para sesiones de velocidad.',
    type: 'Warmup velocidad',
    warmup: [
      'Rodaje suave 8 minutos.',
      'Movilidad dinámica de tobillo, cadera y columna 5 minutos.',
      'Activación glúteo medio 2 x 10 por lado.',
    ],
    mainSet: [
      '3 progresivos de 80 m al 60%, 75% y 85%.',
      '3 salidas cortas de 10 m.',
      '2 aceleraciones de 20 m con recuperación completa.',
    ],
    complementary: [
      'Respiración corta de enfoque 1 minuto.',
      'Revisar postura baja antes de iniciar bloque principal.',
    ],
    technicalCues: [
      'Activar sin fatigar.',
      'Buscar precisión.',
      'Cada repetición debe sentirse más rápida y limpia.',
    ],
    commonErrors: [
      'Hacer demasiados progresivos.',
      'Llegar fatigado al bloque principal.',
      'Acelerar sin control técnico.',
    ],
    cutCriteria: [
      'Piernas pesadas.',
      'Pérdida de coordinación.',
      'Dolor en Aquiles, rodilla o aductor.',
    ],
    coachNotes:
        'Usar antes de salidas, aceleraciones, flying sprints y sesiones neurales.',
    skatingSession: true,
    gymSession: false,
    cyclingSession: false,
    recoverySession: false,
    neuralFocused: true,
    metabolicFocused: false,
    reactiveFocused: true,
    technicalFocused: true,
    taperCompatible: true,
    tags: ['warmup', 'speed', 'neural', 'activation', 'sprint'],
  ),
  TrainingSessionTemplate(
    id: 'warmup_lactate_001',
    number: 202,
    title: 'Calentamiento progresivo para lactato',
    category: TrainingLibraryCategory.lactate,
    modality: TrainingLibraryModality.universal,
    intensity: TrainingSessionIntensity.moderate,
    objective:
        'Preparar al atleta para esfuerzos lactácidos sin gastar la sesión antes de empezar.',
    type: 'Warmup lactato',
    warmup: [
      'Rodaje suave 12 minutos.',
      'Movilidad dinámica 5 minutos.',
      'Técnica de empuje lateral 2 x 1 minuto.',
    ],
    mainSet: [
      '3 progresivos de 100 m.',
      '1 aceleración de 150 m al 80%.',
      'Recuperación completa antes del bloque principal.',
    ],
    complementary: ['Revisar respiración y ritmo.', 'Hidratación breve.'],
    technicalCues: [
      'Subir intensidad de forma gradual.',
      'No entrar en lactato durante el calentamiento.',
      'Mantener postura estable.',
    ],
    commonErrors: [
      'Hacer los progresivos demasiado fuertes.',
      'Acumular fatiga antes del main set.',
      'No recuperar antes de iniciar.',
    ],
    cutCriteria: [
      'Pulso demasiado alto.',
      'Sensación de lactato prematuro.',
      'Técnica pesada o desordenada.',
    ],
    coachNotes:
        'Ideal antes de 200 m, 300 m, 500 m roto o bloques de repeated sprint.',
    skatingSession: true,
    gymSession: false,
    cyclingSession: false,
    recoverySession: false,
    neuralFocused: true,
    metabolicFocused: true,
    reactiveFocused: false,
    technicalFocused: true,
    taperCompatible: false,
    tags: ['warmup', 'lactate', 'progressive', 'metabolic'],
  ),
  TrainingSessionTemplate(
    id: 'warmup_endurance_001',
    number: 203,
    title: 'Calentamiento aeróbico técnico',
    category: TrainingLibraryCategory.endurance,
    modality: TrainingLibraryModality.endurance,
    intensity: TrainingSessionIntensity.low,
    objective:
        'Preparar cuerpo y técnica para rodajes, tempo controlado o trabajo de fondo.',
    type: 'Warmup endurance',
    warmup: [
      'Rodaje suave 10 a 15 minutos.',
      'Movilidad de tobillo, cadera y columna 5 minutos.',
    ],
    mainSet: [
      '3 bloques de 1 minuto de técnica suave.',
      '2 progresivos de 80 m al 70%.',
      'Rodaje suave 3 minutos antes del bloque principal.',
    ],
    complementary: ['Revisión de hidratación.', 'Chequeo de sensaciones.'],
    technicalCues: [
      'Respirar cómodo.',
      'Empuje limpio.',
      'No subir intensidad antes de tiempo.',
    ],
    commonErrors: [
      'Empezar demasiado rápido.',
      'Omitir movilidad.',
      'Llegar rígido al bloque principal.',
    ],
    cutCriteria: [
      'Pulso alto desde el inicio.',
      'Dolor articular.',
      'Sensación de fatiga no esperada.',
    ],
    coachNotes: '�stil para fondo, tempo, ruta y sesiones técnicas largas.',
    skatingSession: true,
    gymSession: false,
    cyclingSession: false,
    recoverySession: false,
    neuralFocused: false,
    metabolicFocused: false,
    reactiveFocused: false,
    technicalFocused: true,
    taperCompatible: true,
    tags: ['warmup', 'endurance', 'aerobic', 'technical'],
  ),
  TrainingSessionTemplate(
    id: 'warmup_gym_001',
    number: 204,
    title: 'Calentamiento para gimnasio de fuerza',
    category: TrainingLibraryCategory.strength,
    modality: TrainingLibraryModality.universal,
    intensity: TrainingSessionIntensity.low,
    objective:
        'Preparar movilidad, estabilidad y patrones básicos antes de fuerza.',
    type: 'Warmup gimnasio fuerza',
    warmup: [
      'Bicicleta suave o caminata 5 minutos.',
      'Movilidad de tobillo, cadera y columna 6 minutos.',
      'Activación de glúteo 2 x 12.',
    ],
    mainSet: [
      'Bisagra de cadera sin carga 2 x 8.',
      'Sentadilla sin carga 2 x 8.',
      'Plancha frontal 2 x 20 segundos.',
      'Series progresivas del ejercicio principal.',
    ],
    complementary: [
      'Respiración y braceo 1 minuto.',
      'Revisar técnica antes de cargar.',
    ],
    technicalCues: [
      'Preparar, no fatigar.',
      'Priorizar rango limpio.',
      'Cargar progresivamente.',
    ],
    commonErrors: [
      'Pasar directo a carga alta.',
      'No activar glúteo.',
      'Usar movilidad agresiva antes de fuerza.',
    ],
    cutCriteria: [
      'Dolor lumbar.',
      'Rigidez que no mejora.',
      'Técnica insegura en series progresivas.',
    ],
    coachNotes: 'Usar antes de fuerza máxima, unilateral o cadena posterior.',
    skatingSession: false,
    gymSession: true,
    cyclingSession: false,
    recoverySession: false,
    neuralFocused: true,
    metabolicFocused: false,
    reactiveFocused: false,
    technicalFocused: true,
    taperCompatible: true,
    tags: ['warmup', 'gym', 'strength', 'mobility', 'activation'],
  ),
  TrainingSessionTemplate(
    id: 'warmup_power_001',
    number: 205,
    title: 'Calentamiento para potencia y pliometría',
    category: TrainingLibraryCategory.power,
    modality: TrainingLibraryModality.universal,
    intensity: TrainingSessionIntensity.moderate,
    objective:
        'Preparar reactividad, rigidez elástica y coordinación para potencia o saltos.',
    type: 'Warmup potencia',
    warmup: [
      'Rodaje o bicicleta suave 5 minutos.',
      'Movilidad dinámica de tobillo y cadera 5 minutos.',
      'Activación de glúteo y core 2 x 10.',
    ],
    mainSet: [
      'Pogos suaves 2 x 12.',
      'Saltos verticales suaves 2 x 5.',
      'Saltos laterales submáximos 2 x 4 por lado.',
      '2 aceleraciones cortas o gestos explosivos al 80%.',
    ],
    complementary: ['Descanso completo 2 minutos antes del bloque principal.'],
    technicalCues: [
      'Aterrizar silencioso.',
      'Buscar elasticidad, no fatiga.',
      'Cortar si baja la calidad.',
    ],
    commonErrors: [
      'Demasiado volumen reactivo.',
      'Aterrizajes duros.',
      'Entrar cansado al bloque principal.',
    ],
    cutCriteria: [
      'Dolor en Aquiles o rodilla.',
      'Aterrizaje ruidoso.',
      'Pérdida de coordinación.',
    ],
    coachNotes:
        'Usar antes de pliometría, contrastes, saltos y potencia. No usar si hay protección reactiva activa.',
    skatingSession: false,
    gymSession: true,
    cyclingSession: false,
    recoverySession: false,
    neuralFocused: true,
    metabolicFocused: false,
    reactiveFocused: true,
    technicalFocused: true,
    taperCompatible: true,
    tags: ['warmup', 'power', 'plyometric', 'reactive', 'activation'],
  ),
];


