// lib/training_library/cycling/cycling_sessions_block_1.dart

import '../training_library_models.dart';

final List<TrainingSessionTemplate> cyclingSessionsBlock1 = [
  TrainingSessionTemplate(
    id: 'cycling_050',
    number: 50,
    title: 'Bicicleta regenerativa 45 min',
    category: TrainingLibraryCategory.cycling,
    modality: TrainingLibraryModality.universal,
    intensity: TrainingSessionIntensity.recovery,
    objective: 'Favorecer recuperación activa sin generar fatiga adicional.',
    type: 'Cycling recovery',
    warmup: ['Pedaleo suave 10 minutos.', 'Cadencia progresiva ligera.'],
    mainSet: [
      '45 minutos en Z1.',
      'Cadencia cómoda y estable.',
      'Sin resistencia alta.',
    ],
    complementary: [
      'Movilidad de tobillo 3 minutos.',
      'Respiración nasal 3 minutos.',
    ],
    technicalCues: [
      'Pedaleo relajado.',
      'Mantener baja percepción de esfuerzo.',
      'Respiración controlada.',
    ],
    commonErrors: [
      'Subir intensidad.',
      'Usar demasiada resistencia.',
      'Cadencia muy baja.',
    ],
    cutCriteria: [
      'Pulso fuera de Z1/Z2.',
      'Fatiga creciente.',
      'Dolor de rodilla o lumbar.',
    ],
    coachNotes:
        'Ideal después de sesiones de lactato, fuerza pesada o competencia.',
    skatingSession: false,
    gymSession: false,
    cyclingSession: true,
    recoverySession: true,
    neuralFocused: false,
    metabolicFocused: false,
    reactiveFocused: false,
    technicalFocused: false,
    taperCompatible: true,
    tags: ['cycling', 'recovery', 'z1', 'regeneration'],
  ),

  TrainingSessionTemplate(
    id: 'cycling_051',
    number: 51,
    title: 'Bicicleta aeróbica 60 km',
    category: TrainingLibraryCategory.cycling,
    modality: TrainingLibraryModality.endurance,
    intensity: TrainingSessionIntensity.moderate,
    objective: 'Desarrollar capacidad aeróbica y resistencia general.',
    type: 'Aerobic cycling',
    warmup: ['Pedaleo suave 15 minutos.', 'Cadencia progresiva.'],
    mainSet: [
      '60 km continuos.',
      'Mantener Z2 estable.',
      'Cadencia eficiente y relajada.',
    ],
    complementary: [
      'Movilidad de cadera 5 minutos.',
      'Estiramiento suave posterior.',
    ],
    technicalCues: [
      'No exceder zona aeróbica.',
      'Pedaleo fluido.',
      'Hidratación constante.',
    ],
    commonErrors: [
      'Convertirlo en tempo.',
      'Cadencia excesivamente baja.',
      'Mala hidratación.',
    ],
    cutCriteria: [
      'Pulso demasiado alto.',
      'Fatiga excesiva.',
      'Dolor articular.',
    ],
    coachNotes: 'Más útil en fondistas y fases generales de preparación.',
    skatingSession: false,
    gymSession: false,
    cyclingSession: true,
    recoverySession: false,
    neuralFocused: false,
    metabolicFocused: true,
    reactiveFocused: false,
    technicalFocused: false,
    taperCompatible: false,
    tags: ['cycling', 'aerobic', 'endurance', 'z2'],
  ),

  TrainingSessionTemplate(
    id: 'cycling_098',
    number: 98,
    title: 'Bicicleta tempo 3 x 12 minutos',
    category: TrainingLibraryCategory.cycling,
    modality: TrainingLibraryModality.mixed,
    intensity: TrainingSessionIntensity.high,
    objective:
        'Desarrollar capacidad aeróbica intensa y tolerancia metabólica.',
    type: 'Tempo cycling',
    warmup: ['15 minutos suaves.', '3 progresiones de 30 segundos.'],
    mainSet: [
      '3 x 12 minutos en Z3/Z4.',
      'Recuperación 4 minutos suaves.',
      'Cadencia constante.',
    ],
    complementary: [
      'Pedaleo suave 10 minutos.',
      'Movilidad de cadera y lumbar.',
    ],
    technicalCues: [
      'Controlar ritmo.',
      'No iniciar demasiado fuerte.',
      'Mantener técnica eficiente.',
    ],
    commonErrors: [
      'Entrar en intensidad máxima.',
      'Cadencia descontrolada.',
      'Recuperación insuficiente.',
    ],
    cutCriteria: [
      'Pérdida marcada de potencia.',
      'Dolor de rodilla.',
      'Fatiga extrema.',
    ],
    coachNotes:
        'Puede generar carga metabólica importante. Vigilar ACWR y readiness.',
    skatingSession: false,
    gymSession: false,
    cyclingSession: true,
    recoverySession: false,
    neuralFocused: false,
    metabolicFocused: true,
    reactiveFocused: false,
    technicalFocused: false,
    taperCompatible: false,
    tags: ['cycling', 'tempo', 'metabolic', 'z3', 'z4'],
  ),

  TrainingSessionTemplate(
    id: 'cycling_099',
    number: 99,
    title: 'Bicicleta descarga 30 minutos',
    category: TrainingLibraryCategory.cycling,
    modality: TrainingLibraryModality.universal,
    intensity: TrainingSessionIntensity.recovery,
    objective: 'Promover circulación y recuperación sin carga significativa.',
    type: 'Recovery cycling',
    warmup: ['Pedaleo suave 5 minutos.'],
    mainSet: ['30 minutos en Z1.', 'Cadencia cómoda.', 'Sin resistencia alta.'],
    complementary: [
      'Respiración 90/90 3 minutos.',
      'Movilidad global 5 minutos.',
    ],
    technicalCues: [
      'Sensación muy fácil.',
      'Respiración relajada.',
      'Piernas sueltas.',
    ],
    commonErrors: [
      'Aumentar intensidad.',
      'Usar demasiada carga.',
      'Buscar fatiga.',
    ],
    cutCriteria: [
      'Pulso fuera de control.',
      'Dolor muscular creciente.',
      'Fatiga posterior.',
    ],
    coachNotes: 'Debe dejar sensación de recuperación, no de entrenamiento.',
    skatingSession: false,
    gymSession: false,
    cyclingSession: true,
    recoverySession: true,
    neuralFocused: false,
    metabolicFocused: false,
    reactiveFocused: false,
    technicalFocused: false,
    taperCompatible: true,
    tags: ['cycling', 'recovery', 'deload', 'z1'],
  ),
];


