// lib/training_library/gym/gym_strength_sessions_block_1.dart

import '../training_library_models.dart';

final List<TrainingSessionTemplate> gymStrengthSessionsBlock1 = [
  TrainingSessionTemplate(
    id: 'strength_017',
    number: 17,
    title: 'Zancada lateral con polea',
    category: TrainingLibraryCategory.strength,
    modality: TrainingLibraryModality.universal,
    intensity: TrainingSessionIntensity.moderate,
    objective: 'Fortalecer empuje lateral específico y control de cadera.',
    type: 'Gimnasio fuerza específica',
    warmup: [
      'Movilidad de cadera 5 minutos.',
      'Activación de glúteo medio 2 x 12 por lado.',
    ],
    mainSet: [
      'Zancada lateral con polea 4 x 8 por lado.',
      'Pausa de 1 segundo en posición baja.',
    ],
    complementary: [
      'Caminata lateral con minibanda 2 x 12 por lado.',
      'Plancha lateral 2 x 30 segundos por lado.',
    ],
    technicalCues: [
      'Empujar el suelo lateralmente.',
      'Rodilla alineada con el pie.',
      'Cadera atrás y tronco estable.',
    ],
    commonErrors: [
      'Colapsar rodilla hacia adentro.',
      'Perder postura baja.',
      'Tirar con brazos en vez de empujar con pierna.',
    ],
    cutCriteria: [
      'Dolor de rodilla o aductor.',
      'Pérdida de control de cadera.',
      'Compensación lumbar.',
    ],
    coachNotes:
        'Ejercicio útil para transferir fuerza al empuje lateral del patinaje.',
    skatingSession: false,
    gymSession: true,
    cyclingSession: false,
    recoverySession: false,
    neuralFocused: true,
    metabolicFocused: false,
    reactiveFocused: false,
    technicalFocused: true,
    taperCompatible: false,
    tags: ['strength', 'lateral-push', 'hip', 'adductor', 'specific'],
  ),
  TrainingSessionTemplate(
    id: 'strength_018',
    number: 18,
    title: 'Empuje de curva con polea',
    category: TrainingLibraryCategory.strength,
    modality: TrainingLibraryModality.universal,
    intensity: TrainingSessionIntensity.moderate,
    objective:
        'Fortalecer patrón de empuje específico de curva y estabilidad pélvica.',
    type: 'Gimnasio fuerza específica curva',
    warmup: [
      'Movilidad de cadera y tobillo 5 minutos.',
      'Sostenido de curva sin carga 2 x 20 segundos por lado.',
    ],
    mainSet: [
      'Empuje de curva con polea 4 x 8 por lado.',
      'Mantener postura baja controlada.',
    ],
    complementary: [
      'Pallof press 2 x 10 por lado.',
      'Copenhagen corto 2 x 20 segundos por lado.',
    ],
    technicalCues: [
      'Empuje largo y lateral.',
      'Pelvis estable.',
      'No girar el tronco.',
    ],
    commonErrors: [
      'Perder eje de rodilla.',
      'Rotar el tronco.',
      'Hacer el gesto rápido sin control.',
    ],
    cutCriteria: [
      'Dolor de aductor.',
      'Dolor lumbar.',
      'Pérdida técnica repetida.',
    ],
    coachNotes:
        'Muy útil para trabajo de curva, pero controlar carga de aductores.',
    skatingSession: false,
    gymSession: true,
    cyclingSession: false,
    recoverySession: false,
    neuralFocused: true,
    metabolicFocused: false,
    reactiveFocused: false,
    technicalFocused: true,
    taperCompatible: false,
    tags: ['strength', 'curve', 'adductor', 'hip', 'specific'],
  ),
  TrainingSessionTemplate(
    id: 'strength_019',
    number: 19,
    title: 'Flexión de cadera con banda',
    category: TrainingLibraryCategory.strength,
    modality: TrainingLibraryModality.universal,
    intensity: TrainingSessionIntensity.low,
    objective:
        'Fortalecer flexores de cadera para recuperación eficiente de pierna.',
    type: 'Fuerza auxiliar',
    warmup: [
      'Movilidad de cadera 4 minutos.',
      'Marcha técnica 2 x 12 por lado.',
    ],
    mainSet: [
      'Flexión de cadera con banda 3 x 12 por lado.',
      'Pausa arriba de 1 segundo.',
    ],
    complementary: [
      'Dead bug 2 x 10 por lado.',
      'Estiramiento suave de psoas 2 x 25 segundos.',
    ],
    technicalCues: [
      'Pelvis quieta.',
      'Subir rodilla sin arquear lumbar.',
      'Controlar la bajada.',
    ],
    commonErrors: [
      'Inclinar el tronco atrás.',
      'Compensar con lumbar.',
      'Usar banda demasiado fuerte.',
    ],
    cutCriteria: [
      'Dolor anterior de cadera.',
      'Pinzamiento.',
      'Pérdida de control pélvico.',
    ],
    coachNotes:
        '�stil como accesorio técnico y preventivo, no debe generar fatiga alta.',
    skatingSession: false,
    gymSession: true,
    cyclingSession: false,
    recoverySession: false,
    neuralFocused: false,
    metabolicFocused: false,
    reactiveFocused: false,
    technicalFocused: true,
    taperCompatible: true,
    tags: ['strength', 'hip-flexor', 'prehab', 'technique'],
  ),
  TrainingSessionTemplate(
    id: 'strength_020',
    number: 20,
    title: 'Tibial raises',
    category: TrainingLibraryCategory.prehab,
    modality: TrainingLibraryModality.universal,
    intensity: TrainingSessionIntensity.low,
    objective:
        'Fortalecer tibial anterior y mejorar tolerancia distal del tobillo.',
    type: 'Prehab distal',
    warmup: [
      'Movilidad de tobillo 3 minutos.',
      'Caminata en talones 2 x 15 metros.',
    ],
    mainSet: [
      'Tibial raises 3 x 15.',
      'Pausa arriba de 1 segundo.',
      'Controlar bajada.',
    ],
    complementary: [
      'Elevación de gemelo 2 x 12.',
      'Liberación plantar 1 minuto por pie.',
    ],
    technicalCues: [
      'Mantener talones apoyados.',
      'Subir puntas de pies con control.',
      'No bloquear rodillas.',
    ],
    commonErrors: [
      'Rebotar.',
      'Perder rango.',
      'Hacerlo con dolor anterior de tobillo.',
    ],
    cutCriteria: [
      'Dolor tibial agudo.',
      'Molestia en empeine.',
      'Fatiga distal excesiva.',
    ],
    coachNotes:
        'Bueno para prevención, pero controlar si ya hay mucha carga de patines.',
    skatingSession: false,
    gymSession: true,
    cyclingSession: false,
    recoverySession: false,
    neuralFocused: false,
    metabolicFocused: false,
    reactiveFocused: false,
    technicalFocused: false,
    taperCompatible: true,
    tags: ['prehab', 'tibial', 'ankle', 'distal-load'],
  ),
  TrainingSessionTemplate(
    id: 'strength_041',
    number: 41,
    title: 'Sentadilla profunda controlada',
    category: TrainingLibraryCategory.strength,
    modality: TrainingLibraryModality.universal,
    intensity: TrainingSessionIntensity.high,
    objective:
        'Desarrollar fuerza general de piernas y control en rangos profundos.',
    type: 'Gimnasio fuerza básica',
    warmup: [
      'Movilidad de tobillo, cadera y columna 8 minutos.',
      'Sentadilla sin carga 2 x 8.',
    ],
    mainSet: [
      'Sentadilla profunda controlada 4 x 5.',
      'Tempo 3 segundos bajada, subida firme.',
    ],
    complementary: [
      'Core anti-extensión 2 x 30 segundos.',
      'Movilidad de cadera 4 minutos.',
    ],
    technicalCues: [
      'Tronco estable.',
      'Rodillas siguen línea de pies.',
      'Peso repartido en todo el pie.',
    ],
    commonErrors: [
      'Colapsar rodillas.',
      'Perder lumbar neutra.',
      'Buscar carga antes que control.',
    ],
    cutCriteria: [
      'Dolor lumbar.',
      'Dolor de rodilla.',
      'Pérdida de profundidad segura.',
    ],
    coachNotes:
        'No ubicar antes de velocidad máxima si genera fatiga residual alta.',
    skatingSession: false,
    gymSession: true,
    cyclingSession: false,
    recoverySession: false,
    neuralFocused: true,
    metabolicFocused: false,
    reactiveFocused: false,
    technicalFocused: true,
    taperCompatible: false,
    tags: ['strength', 'squat', 'legs', 'neural-load'],
  ),
  TrainingSessionTemplate(
    id: 'strength_042',
    number: 42,
    title: 'Peso muerto rumano',
    category: TrainingLibraryCategory.strength,
    modality: TrainingLibraryModality.universal,
    intensity: TrainingSessionIntensity.high,
    objective: 'Fortalecer cadena posterior, isquios y control de bisagra.',
    type: 'Gimnasio fuerza posterior',
    warmup: ['Bisagra sin carga 2 x 10.', 'Puente de glúteo 2 x 12.'],
    mainSet: [
      'Peso muerto rumano 4 x 6.',
      'Bajada controlada.',
      'Recuperación 2 minutos.',
    ],
    complementary: ['Curl femoral fitball 2 x 10.', 'Bird dog 2 x 8 por lado.'],
    technicalCues: [
      'Cadera atrás.',
      'Espalda neutra.',
      'Sentir tensión en isquios, no en lumbar.',
    ],
    commonErrors: [
      'Redondear espalda.',
      'Bajar más de lo controlable.',
      'Flexionar demasiado rodillas.',
    ],
    cutCriteria: [
      'Dolor lumbar.',
      'Tirón en isquio.',
      'Pérdida de control de barra.',
    ],
    coachNotes:
        'Alta carga posterior. Evitar combinar con lactato fuerte o fondo largo inmediato.',
    skatingSession: false,
    gymSession: true,
    cyclingSession: false,
    recoverySession: false,
    neuralFocused: true,
    metabolicFocused: false,
    reactiveFocused: false,
    technicalFocused: true,
    taperCompatible: false,
    tags: ['strength', 'posterior-chain', 'hamstrings', 'hip-hinge'],
  ),
  TrainingSessionTemplate(
    id: 'strength_043',
    number: 43,
    title: 'Hip thrust',
    category: TrainingLibraryCategory.strength,
    modality: TrainingLibraryModality.universal,
    intensity: TrainingSessionIntensity.high,
    objective:
        'Desarrollar fuerza de glúteo y extensión de cadera para el empuje.',
    type: 'Gimnasio fuerza posterior',
    warmup: ['Puente de glúteo 2 x 12.', 'Movilidad de cadera 4 minutos.'],
    mainSet: [
      'Hip thrust 4 x 6.',
      'Pausa arriba de 1 segundo.',
      'Recuperación 2 minutos.',
    ],
    complementary: [
      'Caminata lateral con minibanda 2 x 12.',
      'Plancha frontal 2 x 30 segundos.',
    ],
    technicalCues: [
      'Extender cadera sin arquear lumbar.',
      'Mentón ligeramente recogido.',
      'Empujar desde talones.',
    ],
    commonErrors: [
      'Hiperextender lumbar.',
      'No bloquear cadera.',
      'Usar carga excesiva.',
    ],
    cutCriteria: [
      'Dolor lumbar.',
      'Molestia en cadera.',
      'Pérdida de control.',
    ],
    coachNotes:
        'Buen complemento de fuerza para velocistas y fondistas, dosificar cerca de competencia.',
    skatingSession: false,
    gymSession: true,
    cyclingSession: false,
    recoverySession: false,
    neuralFocused: true,
    metabolicFocused: false,
    reactiveFocused: false,
    technicalFocused: false,
    taperCompatible: false,
    tags: ['strength', 'glutes', 'hip-extension', 'posterior-chain'],
  ),
  TrainingSessionTemplate(
    id: 'strength_044',
    number: 44,
    title: 'Split squat',
    category: TrainingLibraryCategory.strength,
    modality: TrainingLibraryModality.universal,
    intensity: TrainingSessionIntensity.high,
    objective: 'Mejorar fuerza unilateral y estabilidad de cadera y rodilla.',
    type: 'Gimnasio fuerza unilateral',
    warmup: [
      'Movilidad de cadera y tobillo 5 minutos.',
      'Split squat sin carga 2 x 8 por lado.',
    ],
    mainSet: [
      'Split squat 4 x 6 por lado.',
      'Bajada controlada.',
      'Recuperación 90 segundos.',
    ],
    complementary: [
      'Elevación de gemelo unilateral 2 x 12.',
      'Pallof press 2 x 10 por lado.',
    ],
    technicalCues: [
      'Rodilla estable.',
      'Cadera cuadrada.',
      'Empujar el suelo con todo el pie.',
    ],
    commonErrors: [
      'Colapsar rodilla.',
      'Inclinar demasiado el tronco.',
      'Perder equilibrio.',
    ],
    cutCriteria: [
      'Dolor de rodilla.',
      'Dolor de aductor.',
      'Pérdida de alineación.',
    ],
    coachNotes:
        'Ejercicio de alta transferencia, pero puede dejar fatiga unilateral importante.',
    skatingSession: false,
    gymSession: true,
    cyclingSession: false,
    recoverySession: false,
    neuralFocused: true,
    metabolicFocused: false,
    reactiveFocused: false,
    technicalFocused: true,
    taperCompatible: false,
    tags: ['strength', 'unilateral', 'knee-control', 'hip'],
  ),
  TrainingSessionTemplate(
    id: 'strength_045',
    number: 45,
    title: 'Step down lateral',
    category: TrainingLibraryCategory.strength,
    modality: TrainingLibraryModality.universal,
    intensity: TrainingSessionIntensity.moderate,
    objective: 'Mejorar control excéntrico lateral de rodilla y cadera.',
    type: 'Fuerza excéntrica / control',
    warmup: [
      'Movilidad de tobillo 3 minutos.',
      'Sentadilla unilateral asistida 2 x 6 por lado.',
    ],
    mainSet: [
      'Step down lateral 3 x 8 por lado.',
      'Bajada lenta de 3 segundos.',
    ],
    complementary: [
      'Caminata lateral con minibanda 2 x 12.',
      'Tibial raises 2 x 15.',
    ],
    technicalCues: [
      'Rodilla alineada.',
      'Pelvis nivelada.',
      'Tocar el suelo suave.',
    ],
    commonErrors: ['Caer rápido.', 'Colapsar rodilla.', 'Inclinar pelvis.'],
    cutCriteria: [
      'Dolor rotuliano.',
      'Pérdida de control.',
      'Molestia tendinosa.',
    ],
    coachNotes: 'Muy bueno para prevención y control de apoyo en curva.',
    skatingSession: false,
    gymSession: true,
    cyclingSession: false,
    recoverySession: false,
    neuralFocused: false,
    metabolicFocused: false,
    reactiveFocused: false,
    technicalFocused: true,
    taperCompatible: true,
    tags: ['strength', 'eccentric', 'knee-control', 'lateral'],
  ),
  TrainingSessionTemplate(
    id: 'strength_090',
    number: 90,
    title: 'Copenhagen plank corto',
    category: TrainingLibraryCategory.prehab,
    modality: TrainingLibraryModality.universal,
    intensity: TrainingSessionIntensity.moderate,
    objective: 'Fortalecer aductores y estabilidad lateral de pelvis.',
    type: 'Prehab aductores',
    warmup: [
      'Movilidad de cadera 4 minutos.',
      'Plancha lateral simple 2 x 20 segundos por lado.',
    ],
    mainSet: ['Copenhagen plank corto 3 x 20 segundos por lado.'],
    complementary: [
      'Movilidad de aductores suave 2 x 25 segundos.',
      'Pallof press 2 x 10 por lado.',
    ],
    technicalCues: [
      'Cadera alta.',
      'Tronco alineado.',
      'No compensar con lumbar.',
    ],
    commonErrors: [
      'Dejar caer pelvis.',
      'Sentir dolor en aductor.',
      'Rotar el tronco.',
    ],
    cutCriteria: [
      'Dolor de aductor.',
      'Tirón inguinal.',
      'Pérdida de control.',
    ],
    coachNotes: 'Controlar volumen si hay muchas curvas o trabajo lateral.',
    skatingSession: false,
    gymSession: true,
    cyclingSession: false,
    recoverySession: false,
    neuralFocused: false,
    metabolicFocused: false,
    reactiveFocused: false,
    technicalFocused: true,
    taperCompatible: true,
    tags: ['prehab', 'adductor', 'core', 'curve-protection'],
  ),
  TrainingSessionTemplate(
    id: 'strength_091',
    number: 91,
    title: 'Caminata lateral con minibanda',
    category: TrainingLibraryCategory.prehab,
    modality: TrainingLibraryModality.universal,
    intensity: TrainingSessionIntensity.low,
    objective: 'Activar glúteo medio y mejorar control lateral de cadera.',
    type: 'Activación / prehab',
    warmup: ['Movilidad de cadera 3 minutos.', 'Sentadilla sin carga 2 x 8.'],
    mainSet: ['Caminata lateral con minibanda 3 x 12 pasos por lado.'],
    complementary: [
      'Puente de glúteo 2 x 12.',
      'Plancha lateral 2 x 25 segundos.',
    ],
    technicalCues: [
      'Pies paralelos.',
      'Cadera estable.',
      'Tensión constante en banda.',
    ],
    commonErrors: [
      'Juntar rodillas.',
      'Mover el tronco demasiado.',
      'Usar banda excesiva.',
    ],
    cutCriteria: [
      'Dolor lateral de cadera.',
      'Molestia de rodilla.',
      'Fatiga que altera técnica.',
    ],
    coachNotes: 'Puede usarse en calentamiento o prehab, carga baja.',
    skatingSession: false,
    gymSession: true,
    cyclingSession: false,
    recoverySession: false,
    neuralFocused: false,
    metabolicFocused: false,
    reactiveFocused: false,
    technicalFocused: true,
    taperCompatible: true,
    tags: ['prehab', 'glute-med', 'hip-control', 'activation'],
  ),
  TrainingSessionTemplate(
    id: 'strength_092',
    number: 92,
    title: 'Nordic curl asistido',
    category: TrainingLibraryCategory.strength,
    modality: TrainingLibraryModality.universal,
    intensity: TrainingSessionIntensity.high,
    objective: 'Mejorar fuerza excéntrica de isquios y prevención de lesiones.',
    type: 'Fuerza excéntrica posterior',
    warmup: ['Bisagra sin carga 2 x 10.', 'Curl femoral suave 2 x 10.'],
    mainSet: ['Nordic curl asistido 3 x 5.', 'Bajada lenta y controlada.'],
    complementary: ['Puente de glúteo 2 x 12.', 'Movilidad posterior suave.'],
    technicalCues: [
      'Cuerpo en línea.',
      'Controlar la bajada.',
      'Usar asistencia suficiente.',
    ],
    commonErrors: [
      'Caer sin control.',
      'Arquear lumbar.',
      'Hacer demasiadas repeticiones.',
    ],
    cutCriteria: [
      'Dolor o tirón en isquios.',
      'Calambre fuerte.',
      'Pérdida total de control.',
    ],
    coachNotes:
        'Muy demandante. No usar cerca de sesiones máximas de velocidad si deja agujetas.',
    skatingSession: false,
    gymSession: true,
    cyclingSession: false,
    recoverySession: false,
    neuralFocused: true,
    metabolicFocused: false,
    reactiveFocused: false,
    technicalFocused: true,
    taperCompatible: false,
    tags: ['strength', 'hamstrings', 'eccentric', 'injury-prevention'],
  ),
  TrainingSessionTemplate(
    id: 'strength_093',
    number: 93,
    title: 'Curl femoral con fitball',
    category: TrainingLibraryCategory.strength,
    modality: TrainingLibraryModality.universal,
    intensity: TrainingSessionIntensity.moderate,
    objective: 'Fortalecer isquios y control lumbo-pélvico.',
    type: 'Fuerza posterior auxiliar',
    warmup: ['Puente de glúteo 2 x 12.', 'Movilidad posterior 3 minutos.'],
    mainSet: [
      'Curl femoral con fitball 3 x 10.',
      'Controlar extensión y flexión.',
    ],
    complementary: [
      'Plancha frontal 2 x 30 segundos.',
      'Estiramiento suave de isquios.',
    ],
    technicalCues: ['Cadera alta.', 'Movimiento lento.', 'No arquear lumbar.'],
    commonErrors: [
      'Dejar caer cadera.',
      'Mover rápido.',
      'Compensar con lumbar.',
    ],
    cutCriteria: [
      'Calambre persistente.',
      'Dolor lumbar.',
      'Pérdida de control.',
    ],
    coachNotes: 'Accesorio útil con menor carga que nordic o peso muerto.',
    skatingSession: false,
    gymSession: true,
    cyclingSession: false,
    recoverySession: false,
    neuralFocused: false,
    metabolicFocused: false,
    reactiveFocused: false,
    technicalFocused: true,
    taperCompatible: true,
    tags: ['strength', 'hamstrings', 'fitball', 'posterior-chain'],
  ),
  TrainingSessionTemplate(
    id: 'strength_116',
    number: 116,
    title: 'Marcha con banda en posición baja',
    category: TrainingLibraryCategory.strength,
    modality: TrainingLibraryModality.universal,
    intensity: TrainingSessionIntensity.low,
    objective: 'Mejorar estabilidad en postura baja y control de cadera.',
    type: 'Fuerza técnica auxiliar',
    warmup: [
      'Movilidad de cadera 4 minutos.',
      'Posición baja sostenida 2 x 20 segundos.',
    ],
    mainSet: ['Marcha con banda en posición baja 3 x 12 pasos por lado.'],
    complementary: [
      'Pallof press 2 x 10 por lado.',
      'Movilidad psoas 2 x 25 segundos.',
    ],
    technicalCues: ['Cadera estable.', 'Tronco firme.', 'Pasos controlados.'],
    commonErrors: [
      'Subir demasiado la postura.',
      'Balancear tronco.',
      'Perder alineación de rodilla.',
    ],
    cutCriteria: [
      'Dolor lumbar.',
      'Fatiga técnica excesiva.',
      'Molestia de cadera.',
    ],
    coachNotes:
        'Buena para técnica y control, especialmente en jóvenes o retorno de carga.',
    skatingSession: false,
    gymSession: true,
    cyclingSession: false,
    recoverySession: false,
    neuralFocused: false,
    metabolicFocused: false,
    reactiveFocused: false,
    technicalFocused: true,
    taperCompatible: true,
    tags: ['strength', 'low-position', 'hip-control', 'technique'],
  ),
  TrainingSessionTemplate(
    id: 'strength_117',
    number: 117,
    title: 'Isométrico de flexión de cadera',
    category: TrainingLibraryCategory.prehab,
    modality: TrainingLibraryModality.universal,
    intensity: TrainingSessionIntensity.low,
    objective:
        'Mejorar fuerza isométrica de flexores de cadera sin fatiga alta.',
    type: 'Prehab flexor de cadera',
    warmup: [
      'Movilidad de cadera 3 minutos.',
      'Marcha técnica 2 x 10 por lado.',
    ],
    mainSet: ['Isométrico de flexión de cadera 3 x 20 segundos por lado.'],
    complementary: ['Dead bug 2 x 8 por lado.', 'Respiración 90/90 2 minutos.'],
    technicalCues: [
      'Pelvis estable.',
      'No arquear lumbar.',
      'Presión constante.',
    ],
    commonErrors: [
      'Inclinar tronco.',
      'Aguantar respiración.',
      'Hacer demasiada fuerza.',
    ],
    cutCriteria: [
      'Pinzamiento anterior.',
      'Dolor lumbar.',
      'Temblor excesivo.',
    ],
    coachNotes: 'Compatible con taper si se mantiene suave y técnico.',
    skatingSession: false,
    gymSession: true,
    cyclingSession: false,
    recoverySession: false,
    neuralFocused: false,
    metabolicFocused: false,
    reactiveFocused: false,
    technicalFocused: true,
    taperCompatible: true,
    tags: ['prehab', 'hip-flexor', 'isometric', 'taper'],
  ),
  TrainingSessionTemplate(
    id: 'strength_118',
    number: 118,
    title: 'Elevación de gemelo unilateral',
    category: TrainingLibraryCategory.strength,
    modality: TrainingLibraryModality.universal,
    intensity: TrainingSessionIntensity.moderate,
    objective: 'Fortalecer tríceps sural y tolerancia de tobillo.',
    type: 'Fuerza distal',
    warmup: [
      'Movilidad de tobillo 3 minutos.',
      'Elevaciones bilaterales 2 x 12.',
    ],
    mainSet: [
      'Elevación de gemelo unilateral 3 x 12 por lado.',
      'Pausa arriba de 1 segundo.',
    ],
    complementary: [
      'Tibial raises 2 x 15.',
      'Movilidad de sóleo 2 x 25 segundos.',
    ],
    technicalCues: [
      'Subir completo.',
      'Controlar bajada.',
      'No girar el tobillo.',
    ],
    commonErrors: [
      'Rebotar.',
      'Perder rango.',
      'Cargar solo el borde externo del pie.',
    ],
    cutCriteria: [
      'Dolor en Aquiles.',
      'Dolor plantar.',
      'Calambre persistente.',
    ],
    coachNotes:
        'Controlar con atletas sensibles a Aquiles o mucha carga en pista/ruta.',
    skatingSession: false,
    gymSession: true,
    cyclingSession: false,
    recoverySession: false,
    neuralFocused: false,
    metabolicFocused: false,
    reactiveFocused: false,
    technicalFocused: false,
    taperCompatible: true,
    tags: ['strength', 'calf', 'ankle', 'distal-load'],
  ),
  TrainingSessionTemplate(
    id: 'strength_119',
    number: 119,
    title: 'Equilibrio unilateral con ojos cerrados',
    category: TrainingLibraryCategory.prehab,
    modality: TrainingLibraryModality.universal,
    intensity: TrainingSessionIntensity.low,
    objective: 'Mejorar propiocepción y control de apoyo.',
    type: 'Propiocepción / prehab',
    warmup: [
      'Movilidad de tobillo 2 minutos.',
      'Equilibrio unilateral ojos abiertos 2 x 20 segundos.',
    ],
    mainSet: [
      'Equilibrio unilateral con ojos cerrados 4 x 20 segundos por lado.',
    ],
    complementary: [
      'Step down lateral suave 2 x 6 por lado.',
      'Respiración nasal 2 minutos.',
    ],
    technicalCues: ['Pie activo.', 'Rodilla estable.', 'Respirar lento.'],
    commonErrors: [
      'Bloquear rodilla.',
      'Colapsar arco del pie.',
      'Hacerlo con fatiga alta.',
    ],
    cutCriteria: [
      'Dolor de tobillo.',
      'Pérdida repetida de control.',
      'Mareo.',
    ],
    coachNotes: 'Muy útil en prevención y retorno de lesión, baja carga.',
    skatingSession: false,
    gymSession: true,
    cyclingSession: false,
    recoverySession: false,
    neuralFocused: false,
    metabolicFocused: false,
    reactiveFocused: false,
    technicalFocused: true,
    taperCompatible: true,
    tags: ['prehab', 'balance', 'proprioception', 'ankle'],
  ),
  TrainingSessionTemplate(
    id: 'strength_144',
    number: 144,
    title: 'Sentadilla unilateral asistida',
    category: TrainingLibraryCategory.strength,
    modality: TrainingLibraryModality.universal,
    intensity: TrainingSessionIntensity.moderate,
    objective: 'Desarrollar fuerza unilateral y control de rodilla.',
    type: 'Fuerza unilateral asistida',
    warmup: [
      'Movilidad de tobillo y cadera 5 minutos.',
      'Step down suave 2 x 6 por lado.',
    ],
    mainSet: [
      'Sentadilla unilateral asistida 3 x 6 por lado.',
      'Bajada controlada.',
    ],
    complementary: [
      'Caminata lateral con minibanda 2 x 12.',
      'Pallof press 2 x 10.',
    ],
    technicalCues: [
      'Rodilla alineada.',
      'Pelvis estable.',
      'Usar asistencia para calidad.',
    ],
    commonErrors: ['Perder eje.', 'Bajar sin control.', 'Usar impulso.'],
    cutCriteria: [
      'Dolor rotuliano.',
      'Dolor de cadera.',
      'Pérdida técnica repetida.',
    ],
    coachNotes: 'Progresión útil antes de cargas unilaterales más agresivas.',
    skatingSession: false,
    gymSession: true,
    cyclingSession: false,
    recoverySession: false,
    neuralFocused: true,
    metabolicFocused: false,
    reactiveFocused: false,
    technicalFocused: true,
    taperCompatible: false,
    tags: ['strength', 'unilateral', 'knee-control', 'assisted'],
  ),
  TrainingSessionTemplate(
    id: 'strength_145',
    number: 145,
    title: 'Peso muerto unilateral',
    category: TrainingLibraryCategory.strength,
    modality: TrainingLibraryModality.universal,
    intensity: TrainingSessionIntensity.moderate,
    objective:
        'Fortalecer cadena posterior unilateral y estabilidad de cadera.',
    type: 'Fuerza unilateral posterior',
    warmup: [
      'Bisagra sin carga 2 x 8 por lado.',
      'Equilibrio unilateral 2 x 20 segundos.',
    ],
    mainSet: [
      'Peso muerto unilateral 3 x 8 por lado.',
      'Movimiento lento y controlado.',
    ],
    complementary: ['Bird dog 2 x 8 por lado.', 'Puente de glúteo 2 x 12.'],
    technicalCues: [
      'Cadera cuadrada.',
      'Espalda neutra.',
      'Pie de apoyo estable.',
    ],
    commonErrors: [
      'Rotar pelvis.',
      'Redondear espalda.',
      'Perder equilibrio por exceso de carga.',
    ],
    cutCriteria: ['Dolor lumbar.', 'Tirón posterior.', 'Pérdida de control.'],
    coachNotes:
        'Buena transferencia al control unilateral del apoyo en patinaje.',
    skatingSession: false,
    gymSession: true,
    cyclingSession: false,
    recoverySession: false,
    neuralFocused: true,
    metabolicFocused: false,
    reactiveFocused: false,
    technicalFocused: true,
    taperCompatible: false,
    tags: ['strength', 'unilateral', 'posterior-chain', 'balance'],
  ),
  TrainingSessionTemplate(
    id: 'strength_146',
    number: 146,
    title: 'Remo con banda en posición baja',
    category: TrainingLibraryCategory.strength,
    modality: TrainingLibraryModality.universal,
    intensity: TrainingSessionIntensity.low,
    objective: 'Mejorar estabilidad escapular y postura baja.',
    type: 'Fuerza tren superior / postura',
    warmup: ['Movilidad torácica 3 minutos.', 'Activación escapular 2 x 10.'],
    mainSet: [
      'Remo con banda en posición baja 3 x 12.',
      'Mantener postura estable.',
    ],
    complementary: [
      'Plancha frontal 2 x 30 segundos.',
      'Movilidad torácica 2 x 8.',
    ],
    technicalCues: [
      'Escápulas atrás y abajo.',
      'Cadera estable.',
      'No subir hombros.',
    ],
    commonErrors: [
      'Encoger hombros.',
      'Perder postura baja.',
      'Tirar con lumbar.',
    ],
    cutCriteria: ['Dolor lumbar.', 'Dolor de hombro.', 'Pérdida de postura.'],
    coachNotes:
        'Complemento útil para postura y tren superior sin fatiga alta.',
    skatingSession: false,
    gymSession: true,
    cyclingSession: false,
    recoverySession: false,
    neuralFocused: false,
    metabolicFocused: false,
    reactiveFocused: false,
    technicalFocused: true,
    taperCompatible: true,
    tags: ['strength', 'upper-body', 'posture', 'scapular-control'],
  ),
  TrainingSessionTemplate(
    id: 'strength_147',
    number: 147,
    title: 'Push-up con control de core',
    category: TrainingLibraryCategory.strength,
    modality: TrainingLibraryModality.universal,
    intensity: TrainingSessionIntensity.moderate,
    objective: 'Fortalecer tren superior manteniendo control lumbo-pélvico.',
    type: 'Fuerza tren superior / core',
    warmup: [
      'Movilidad de hombro 3 minutos.',
      'Plancha frontal 2 x 20 segundos.',
    ],
    mainSet: [
      'Push-up con control de core 3 x 8 a 12.',
      'Mantener línea corporal.',
    ],
    complementary: [
      'Pallof press 2 x 10 por lado.',
      'Movilidad torácica 2 x 8.',
    ],
    technicalCues: [
      'Costillas abajo.',
      'Glúteos activos.',
      'Codos controlados.',
    ],
    commonErrors: [
      'Hundirse de lumbar.',
      'Abrir demasiado codos.',
      'Perder ritmo respiratorio.',
    ],
    cutCriteria: [
      'Dolor de hombro.',
      'Dolor lumbar.',
      'Pérdida de control del core.',
    ],
    coachNotes:
        '�stil para equilibrio general de fuerza y estabilidad postural.',
    skatingSession: false,
    gymSession: true,
    cyclingSession: false,
    recoverySession: false,
    neuralFocused: false,
    metabolicFocused: false,
    reactiveFocused: false,
    technicalFocused: true,
    taperCompatible: true,
    tags: ['strength', 'upper-body', 'core', 'posture'],
  ),
  TrainingSessionTemplate(
    id: 'strength_167',
    number: 167,
    title: 'Sentadilla lateral',
    category: TrainingLibraryCategory.strength,
    modality: TrainingLibraryModality.universal,
    intensity: TrainingSessionIntensity.moderate,
    objective: 'Fortalecer patrón lateral y movilidad activa de cadera.',
    type: 'Fuerza lateral',
    warmup: [
      'Movilidad de aductores 3 minutos.',
      'Zancada lateral sin carga 2 x 8 por lado.',
    ],
    mainSet: ['Sentadilla lateral 3 x 8 por lado.', 'Controlar profundidad.'],
    complementary: [
      'Copenhagen corto 2 x 20 segundos.',
      'Movilidad psoas 2 x 25 segundos.',
    ],
    technicalCues: [
      'Cadera atrás.',
      'Pierna extendida activa.',
      'Rodilla alineada.',
    ],
    commonErrors: ['Colapsar rodilla.', 'Perder talón.', 'Forzar aductor.'],
    cutCriteria: [
      'Dolor inguinal.',
      'Dolor de rodilla.',
      'Pérdida de control.',
    ],
    coachNotes:
        'Buena para empuje lateral, pero no acumular con demasiada curva/aductores.',
    skatingSession: false,
    gymSession: true,
    cyclingSession: false,
    recoverySession: false,
    neuralFocused: true,
    metabolicFocused: false,
    reactiveFocused: false,
    technicalFocused: true,
    taperCompatible: false,
    tags: ['strength', 'lateral', 'adductor', 'hip'],
  ),
  TrainingSessionTemplate(
    id: 'strength_168',
    number: 168,
    title: 'Polea baja simulando empuje',
    category: TrainingLibraryCategory.strength,
    modality: TrainingLibraryModality.universal,
    intensity: TrainingSessionIntensity.moderate,
    objective: 'Reforzar patrón específico de empuje en postura de patinaje.',
    type: 'Fuerza específica con polea',
    warmup: [
      'Movilidad de cadera 4 minutos.',
      'Posición básica sostenida 2 x 20 segundos.',
    ],
    mainSet: [
      'Polea baja simulando empuje 4 x 8 por lado.',
      'Mantener empuje largo y controlado.',
    ],
    complementary: [
      'Pallof press 2 x 10 por lado.',
      'Movilidad de tobillo 2 x 8.',
    ],
    technicalCues: ['Empuje lateral.', 'Pelvis estable.', 'No girar tronco.'],
    commonErrors: ['Tirar con brazos.', 'Perder postura.', 'Rotar pelvis.'],
    cutCriteria: ['Dolor lumbar.', 'Dolor de aductor.', 'Pérdida de técnica.'],
    coachNotes: 'Alta especificidad técnica. Priorizar calidad sobre carga.',
    skatingSession: false,
    gymSession: true,
    cyclingSession: false,
    recoverySession: false,
    neuralFocused: true,
    metabolicFocused: false,
    reactiveFocused: false,
    technicalFocused: true,
    taperCompatible: false,
    tags: ['strength', 'specific', 'lateral-push', 'skating-position'],
  ),
  TrainingSessionTemplate(
    id: 'strength_171',
    number: 171,
    title: 'Control excéntrico de aductores',
    category: TrainingLibraryCategory.prehab,
    modality: TrainingLibraryModality.universal,
    intensity: TrainingSessionIntensity.moderate,
    objective:
        'Mejorar tolerancia excéntrica de aductores para curvas y empujes laterales.',
    type: 'Prehab aductores excéntrico',
    warmup: [
      'Movilidad suave de aductores 3 minutos.',
      'Copenhagen corto suave 2 x 15 segundos.',
    ],
    mainSet: [
      'Control excéntrico de aductores 3 x 6 por lado.',
      'Bajada lenta y sin dolor.',
    ],
    complementary: [
      'Plancha lateral 2 x 25 segundos.',
      'Movilidad de cadera 3 minutos.',
    ],
    technicalCues: [
      'Controlar el rango.',
      'No buscar dolor.',
      'Pelvis estable.',
    ],
    commonErrors: [
      'Bajar demasiado rápido.',
      'Forzar rango.',
      'Compensar con lumbar.',
    ],
    cutCriteria: [
      'Dolor inguinal.',
      'Tirón en aductor.',
      'Pérdida de control.',
    ],
    coachNotes:
        'No combinar con exceso de curvas intensas si el atleta está sensible de aductores.',
    skatingSession: false,
    gymSession: true,
    cyclingSession: false,
    recoverySession: false,
    neuralFocused: false,
    metabolicFocused: false,
    reactiveFocused: false,
    technicalFocused: true,
    taperCompatible: true,
    tags: ['prehab', 'adductor', 'eccentric', 'curve-protection'],
  ),
  TrainingSessionTemplate(
    id: 'strength_172',
    number: 172,
    title: 'Isométrico de sóleo',
    category: TrainingLibraryCategory.prehab,
    modality: TrainingLibraryModality.universal,
    intensity: TrainingSessionIntensity.low,
    objective:
        'Mejorar tolerancia del sóleo y tendón de Aquiles con baja carga sistémica.',
    type: 'Prehab sóleo / Aquiles',
    warmup: [
      'Movilidad de tobillo 3 minutos.',
      'Elevaciones bilaterales suaves 2 x 10.',
    ],
    mainSet: [
      'Isométrico de sóleo 4 x 30 segundos por lado.',
      'Rodilla flexionada, talón elevado.',
    ],
    complementary: [
      'Tibial raises 2 x 15.',
      'Movilidad de tobillo rodilla a pared 2 x 8.',
    ],
    technicalCues: [
      'Presión estable.',
      'Rodilla flexionada.',
      'No colapsar tobillo.',
    ],
    commonErrors: [
      'Subir demasiado la intensidad.',
      'Bloquear rodilla.',
      'Sentir dolor en Aquiles.',
    ],
    cutCriteria: [
      'Dolor en Aquiles.',
      'Dolor plantar.',
      'Aumento de rigidez posterior.',
    ],
    coachNotes:
        'Muy útil para manejo de carga distal y prevención en semanas con mucho patín.',
    skatingSession: false,
    gymSession: true,
    cyclingSession: false,
    recoverySession: false,
    neuralFocused: false,
    metabolicFocused: false,
    reactiveFocused: false,
    technicalFocused: false,
    taperCompatible: true,
    tags: ['prehab', 'soleus', 'achilles', 'ankle', 'distal-load'],
  ),
];


