import '../training_library_models.dart';

final List<TrainingSessionTemplate> gymPowerSessionsBlock1 = [
  TrainingSessionTemplate(
    id: 'power_052',
    number: 52,
    title: 'Sentadilla con salto con carga ligera',
    category: TrainingLibraryCategory.power,
    modality: TrainingLibraryModality.universal,
    intensity: TrainingSessionIntensity.high,
    objective:
        'Desarrollar potencia de extensión de piernas con baja carga externa.',
    type: 'Gimnasio potencia',
    warmup: [
      'Movilidad de cadera y tobillo 6 minutos.',
      'Sentadilla sin carga 2 x 8.',
      'Saltos suaves 2 x 5.',
    ],
    mainSet: [
      'Sentadilla con salto con carga ligera 4 x 5.',
      'Recuperación 2 minutos.',
      'Buscar máxima velocidad sin perder técnica.',
    ],
    complementary: [
      'Core anti-extensión 2 x 30 segundos.',
      'Movilidad de cadera 3 minutos.',
    ],
    technicalCues: [
      'Aterrizar suave.',
      'Extender fuerte.',
      'Rodillas alineadas.',
    ],
    commonErrors: [
      'Usar demasiada carga.',
      'Aterrizar rígido.',
      'Perder alineación de rodillas.',
    ],
    cutCriteria: [
      'Dolor de rodilla o Aquiles.',
      'Pérdida de altura marcada.',
      'Aterrizaje ruidoso o descontrolado.',
    ],
    coachNotes: 'Mantener volumen bajo. No usar si hay fatiga reactiva alta.',
    skatingSession: false,
    gymSession: true,
    cyclingSession: false,
    recoverySession: false,
    neuralFocused: true,
    metabolicFocused: false,
    reactiveFocused: true,
    technicalFocused: true,
    taperCompatible: false,
    tags: ['power', 'jump', 'reactive', 'legs', 'neural-load'],
  ),
  TrainingSessionTemplate(
    id: 'power_053',
    number: 53,
    title: 'Cargada alta desde muslo',
    category: TrainingLibraryCategory.power,
    modality: TrainingLibraryModality.universal,
    intensity: TrainingSessionIntensity.high,
    objective:
        'Desarrollar potencia de triple extensión y coordinación explosiva.',
    type: 'Gimnasio potencia olímpica',
    warmup: [
      'Movilidad de tobillo, cadera y hombro 8 minutos.',
      'Tirón técnico con barra vacía 3 x 5.',
    ],
    mainSet: [
      'Cargada alta desde muslo 5 x 3.',
      'Recuperación 2 a 3 minutos.',
      'Carga moderada, máxima velocidad.',
    ],
    complementary: [
      'Peso muerto rumano ligero 2 x 6.',
      'Plancha frontal 2 x 30 segundos.',
    ],
    technicalCues: [
      'Barra cerca del cuerpo.',
      'Extensión explosiva.',
      'Recibir estable.',
    ],
    commonErrors: [
      'Tirar con brazos demasiado pronto.',
      'Perder espalda neutra.',
      'Usar carga excesiva.',
    ],
    cutCriteria: [
      'Técnica insegura.',
      'Dolor lumbar o muñeca.',
      'Pérdida de velocidad.',
    ],
    coachNotes:
        'Solo para atletas con técnica suficiente. Priorizar calidad por encima de carga.',
    skatingSession: false,
    gymSession: true,
    cyclingSession: false,
    recoverySession: false,
    neuralFocused: true,
    metabolicFocused: false,
    reactiveFocused: true,
    technicalFocused: true,
    taperCompatible: false,
    tags: ['power', 'olympic-lift', 'triple-extension', 'neural-load'],
  ),
  TrainingSessionTemplate(
    id: 'power_054',
    number: 54,
    title: 'Tirón explosivo con trap bar',
    category: TrainingLibraryCategory.power,
    modality: TrainingLibraryModality.universal,
    intensity: TrainingSessionIntensity.high,
    objective:
        'Desarrollar potencia de extensión de cadera con patrón seguro y explosivo.',
    type: 'Gimnasio potencia con trap bar',
    warmup: [
      'Bisagra de cadera 2 x 8.',
      'Saltos suaves 2 x 5.',
      'Series progresivas con trap bar.',
    ],
    mainSet: [
      'Tirón explosivo con trap bar 5 x 3.',
      'Recuperación 2 a 3 minutos.',
      'Subir con intención máxima.',
    ],
    complementary: ['Hip thrust ligero 2 x 6.', 'Bird dog 2 x 8 por lado.'],
    technicalCues: [
      'Empujar el suelo.',
      'Cadera y rodillas extienden juntas.',
      'Espalda estable.',
    ],
    commonErrors: [
      'Convertirlo en peso muerto lento.',
      'Perder espalda neutra.',
      'Usar carga pesada sin velocidad.',
    ],
    cutCriteria: [
      'Dolor lumbar.',
      'Pérdida clara de velocidad.',
      'Técnica insegura.',
    ],
    coachNotes:
        'Excelente alternativa de potencia si no se domina la halterofilia.',
    skatingSession: false,
    gymSession: true,
    cyclingSession: false,
    recoverySession: false,
    neuralFocused: true,
    metabolicFocused: false,
    reactiveFocused: true,
    technicalFocused: true,
    taperCompatible: false,
    tags: ['power', 'trap-bar', 'hip-extension', 'explosive'],
  ),
  TrainingSessionTemplate(
    id: 'power_055',
    number: 55,
    title: 'Sentadilla pesada + salto lateral',
    category: TrainingLibraryCategory.power,
    modality: TrainingLibraryModality.universal,
    intensity: TrainingSessionIntensity.maximal,
    objective:
        'Estimular contraste fuerza-potencia para mejorar producción explosiva lateral.',
    type: 'Contraste fuerza-potencia',
    warmup: [
      'Movilidad completa 8 minutos.',
      'Sentadilla progresiva 3 series.',
      'Saltos laterales suaves 2 x 4 por lado.',
    ],
    mainSet: [
      '4 bloques: sentadilla pesada 3 repeticiones + salto lateral 4 por lado.',
      'Recuperación 3 minutos entre bloques.',
    ],
    complementary: [
      'Movilidad de cadera 4 minutos.',
      'Respiración 90/90 3 minutos.',
    ],
    technicalCues: [
      'Sentadilla fuerte y limpia.',
      'Salto lateral reactivo.',
      'Aterrizaje estable.',
    ],
    commonErrors: [
      'Fatigar antes de saltar.',
      'Aterrizar con rodilla colapsada.',
      'Usar contraste con técnica pobre.',
    ],
    cutCriteria: [
      'Dolor articular.',
      'Pérdida de velocidad o altura.',
      'Aterrizaje inseguro.',
    ],
    coachNotes:
        'Alta carga neural y reactiva. No programar cerca de lactato fuerte ni con readiness bajo.',
    skatingSession: false,
    gymSession: true,
    cyclingSession: false,
    recoverySession: false,
    neuralFocused: true,
    metabolicFocused: false,
    reactiveFocused: true,
    technicalFocused: true,
    taperCompatible: false,
    tags: ['power', 'contrast', 'heavy-strength', 'lateral-jump', 'reactive'],
  ),
  TrainingSessionTemplate(
    id: 'power_056',
    number: 56,
    title: 'Hip thrust pesado + sprint 30 m',
    category: TrainingLibraryCategory.power,
    modality: TrainingLibraryModality.sprinter,
    intensity: TrainingSessionIntensity.maximal,
    objective:
        'Potenciar extensión de cadera y transferencia a aceleración corta.',
    type: 'Contraste fuerza-velocidad',
    warmup: [
      'Movilidad de cadera 6 minutos.',
      'Activación de glúteo 2 x 12.',
      'Progresivos de carrera 3 x 20 m.',
    ],
    mainSet: [
      '4 bloques: hip thrust pesado 3 repeticiones + sprint 30 m.',
      'Recuperación 3 minutos entre bloques.',
      'Calidad máxima en cada sprint.',
    ],
    complementary: [
      'Movilidad psoas 3 minutos.',
      'Respiración 90/90 3 minutos.',
    ],
    technicalCues: [
      'Extensión fuerte de cadera.',
      'Sprint limpio.',
      'No perseguir fatiga.',
    ],
    commonErrors: [
      'Usar carga que enlentece demasiado.',
      'Sprint con técnica degradada.',
      'Reducir descanso.',
    ],
    cutCriteria: [
      'Pérdida de velocidad.',
      'Dolor lumbar o isquio.',
      'Técnica de sprint deficiente.',
    ],
    coachNotes:
        'Muy útil para velocistas. Evitar en semanas de fatiga alta o antes de sesiones lactácidas.',
    skatingSession: false,
    gymSession: true,
    cyclingSession: false,
    recoverySession: false,
    neuralFocused: true,
    metabolicFocused: false,
    reactiveFocused: true,
    technicalFocused: true,
    taperCompatible: false,
    tags: ['power', 'contrast', 'hip-extension', 'sprint', 'sprinter'],
  ),
];


