import '../training_library_models.dart';

final List<TrainingSessionTemplate> coreSessionsBlock1 = [
  TrainingSessionTemplate(
    id: 'core_021',
    number: 21,
    title: 'Plancha lateral con abducción',
    category: TrainingLibraryCategory.core,
    modality: TrainingLibraryModality.universal,
    intensity: TrainingSessionIntensity.moderate,
    objective: 'Fortalecer oblicuos, glúteo medio y estabilidad lumbo-pélvica.',
    type: 'Core lateral / estabilidad',
    warmup: ['Activación abdominal.', 'Movilidad de cadera.', 'Puente glúteo.'],
    mainSet: ['3 x 20-30 seg por lado.', 'Progresión: elevar pierna superior.'],
    complementary: ['Traslados de cadera.'],
    technicalCues: [
      'Cadera alta.',
      'Costillas cerradas.',
      'No rotes.',
      'Pierna larga.',
    ],
    commonErrors: [
      'Caer de cadera.',
      'Rotar tronco.',
      'Tensión cervical.',
      'Perder respiración.',
    ],
    cutCriteria: [
      'Dolor lumbar.',
      'Temblor excesivo.',
      'No sostiene alineación.',
    ],
    coachNotes: 'Transferencia directa a curva y empuje unilateral.',
    skatingSession: false,
    gymSession: true,
    cyclingSession: false,
    recoverySession: false,
    neuralFocused: false,
    metabolicFocused: false,
    reactiveFocused: false,
    technicalFocused: true,
    taperCompatible: true,
    tags: ['core', 'lateral', 'gluteo medio', 'curva'],
  ),

  TrainingSessionTemplate(
    id: 'core_022',
    number: 22,
    title: 'Dead bug con banda',
    category: TrainingLibraryCategory.core,
    modality: TrainingLibraryModality.universal,
    intensity: TrainingSessionIntensity.low,
    objective: 'Mejorar control del core profundo y estabilidad de pelvis.',
    type: 'Core anti-extensión',
    warmup: ['Respiración diafragmática.', 'Activación transverso.'],
    mainSet: ['3 x 8-10 por lado.', 'Movimiento lento.'],
    complementary: ['Flexión de cadera con banda.'],
    technicalCues: [
      'Espalda pegada.',
      'Respira.',
      'Pelvis quieta.',
      'Mueve lento.',
    ],
    commonErrors: [
      'Arquear lumbar.',
      'Mover muy rápido.',
      'Perder control de costillas.',
      'Tensión de cuello.',
    ],
    cutCriteria: ['Dolor lumbar.', 'No controla pelvis.', 'Fatiga excesiva.'],
    coachNotes: 'Base para mantener postura baja sin romper cintura.',
    skatingSession: false,
    gymSession: true,
    cyclingSession: false,
    recoverySession: false,
    neuralFocused: false,
    metabolicFocused: false,
    reactiveFocused: false,
    technicalFocused: true,
    taperCompatible: true,
    tags: ['core', 'anti extension', 'pelvis', 'postura baja'],
  ),

  TrainingSessionTemplate(
    id: 'core_023',
    number: 23,
    title: 'Pallof press',
    category: TrainingLibraryCategory.core,
    modality: TrainingLibraryModality.universal,
    intensity: TrainingSessionIntensity.low,
    objective: 'Desarrollar antirotación para curvas y empujes laterales.',
    type: 'Core antirotacional',
    warmup: ['Movilidad torácica.', 'Activación oblicuos.'],
    mainSet: ['3 x 10-12 por lado.', 'Pausa 2 seg con brazos extendidos.'],
    complementary: ['Zancada lateral controlada.'],
    technicalCues: [
      'No dejes que la banda te gire.',
      'Cadera firme.',
      'Costillas abajo.',
      'Respira.',
    ],
    commonErrors: [
      'Rotar tronco.',
      'Bloquear hombros.',
      'Hiperextender lumbar.',
      'Usar demasiada carga.',
    ],
    cutCriteria: [
      'Dolor lumbar.',
      'Pérdida de postura.',
      'Compensación de hombros.',
    ],
    coachNotes: 'Excelente para patinadores que se desordenan en curva.',
    skatingSession: false,
    gymSession: true,
    cyclingSession: false,
    recoverySession: false,
    neuralFocused: false,
    metabolicFocused: false,
    reactiveFocused: false,
    technicalFocused: true,
    taperCompatible: true,
    tags: ['core', 'antirotacion', 'curva', 'empuje lateral'],
  ),

  TrainingSessionTemplate(
    id: 'core_046',
    number: 46,
    title: 'Buenos días isométrico',
    category: TrainingLibraryCategory.core,
    modality: TrainingLibraryModality.universal,
    intensity: TrainingSessionIntensity.moderate,
    objective:
        'Fortalecer erectores espinales e isquios para sostener posición baja.',
    type: 'Core posterior / isométrico específico',
    warmup: ['Bisagra de cadera.', 'Movilidad torácica.', 'Activación glúteo.'],
    mainSet: [
      '4 x 20-40 seg en inclinación tipo patinaje.',
      'Recuperación: 60-90 seg.',
    ],
    complementary: ['Respiración diafragmática 2 min.'],
    technicalCues: [
      'Espalda larga.',
      'Cadera atrás.',
      'Costillas controladas.',
      'No redondees.',
    ],
    commonErrors: [
      'Curvar lumbar.',
      'Cargar cuello.',
      'Bloquear rodillas.',
      'Respirar mal.',
    ],
    cutCriteria: ['Dolor lumbar.', 'Hormigueo.', 'No sostiene postura.'],
    coachNotes:
        'Transferencia directa a mantener posición en fondo y velocidad.',
    skatingSession: false,
    gymSession: true,
    cyclingSession: false,
    recoverySession: false,
    neuralFocused: false,
    metabolicFocused: false,
    reactiveFocused: false,
    technicalFocused: true,
    taperCompatible: true,
    tags: ['core', 'posterior', 'isometrico', 'postura baja'],
  ),

  TrainingSessionTemplate(
    id: 'core_047',
    number: 47,
    title: 'Plancha frontal con alcance',
    category: TrainingLibraryCategory.core,
    modality: TrainingLibraryModality.universal,
    intensity: TrainingSessionIntensity.moderate,
    objective: 'Mejorar antirotación y control del tronco.',
    type: 'Core antirotacional',
    warmup: ['Plancha básica 2 x 20 seg.', 'Movilidad hombro.'],
    mainSet: ['3 x 8 alcances por brazo.', 'Mantener pelvis quieta.'],
    complementary: ['Pallof press 2 x 10.'],
    technicalCues: [
      'Pelvis inmóvil.',
      'Empuja el suelo.',
      'Respira.',
      'No gires.',
    ],
    commonErrors: [
      'Rotar cadera.',
      'Hundirse de hombros.',
      'Arquear lumbar.',
      'Mover rápido.',
    ],
    cutCriteria: [
      'Dolor lumbar.',
      'No controla pelvis.',
      'Temblores excesivos.',
    ],
    coachNotes: 'Muy útil para braceo fuerte sin perder línea.',
    skatingSession: false,
    gymSession: true,
    cyclingSession: false,
    recoverySession: false,
    neuralFocused: false,
    metabolicFocused: false,
    reactiveFocused: false,
    technicalFocused: true,
    taperCompatible: true,
    tags: ['core', 'plancha', 'antirotacion', 'braceo'],
  ),

  TrainingSessionTemplate(
    id: 'core_094',
    number: 94,
    title: 'Body saw',
    category: TrainingLibraryCategory.core,
    modality: TrainingLibraryModality.universal,
    intensity: TrainingSessionIntensity.moderate,
    objective: 'Mejorar resistencia del core en posición extendida.',
    type: 'Core anti-extensión',
    warmup: ['Plancha básica.', 'Respiración 90/90.'],
    mainSet: ['3 x 8-12 deslizamientos.', 'Recuperación: 60 seg.'],
    complementary: ['Movilidad psoas.'],
    technicalCues: [
      'Costillas abajo.',
      'Glúteo activo.',
      'No arquees.',
      'Movimiento corto.',
    ],
    commonErrors: [
      'Hundirse lumbar.',
      'Mover demasiado lejos.',
      'Tensión cervical.',
      'No respirar.',
    ],
    cutCriteria: ['Dolor lumbar.', 'No mantiene control.', 'Temblor excesivo.'],
    coachNotes: 'Ayuda a sostener postura baja sin colapsar.',
    skatingSession: false,
    gymSession: true,
    cyclingSession: false,
    recoverySession: false,
    neuralFocused: false,
    metabolicFocused: false,
    reactiveFocused: false,
    technicalFocused: true,
    taperCompatible: true,
    tags: ['core', 'anti extension', 'body saw', 'postura baja'],
  ),

  TrainingSessionTemplate(
    id: 'core_095',
    number: 95,
    title: 'Pallof press en posición de patinaje',
    category: TrainingLibraryCategory.core,
    modality: TrainingLibraryModality.universal,
    intensity: TrainingSessionIntensity.moderate,
    objective: 'Transferir antirotación a postura específica.',
    type: 'Core específico',
    warmup: ['Pallof básico.', 'Posición baja sin carga.'],
    mainSet: ['3 x 10 por lado en posición baja.', 'Pausa 2 seg extendido.'],
    complementary: ['Empuje lateral con banda.'],
    technicalCues: [
      'Cadera baja.',
      'No gires.',
      'Costillas abajo.',
      'Presiona al frente.',
    ],
    commonErrors: [
      'Subir postura.',
      'Rotar hombros.',
      'Arqueo lumbar.',
      'Carga excesiva.',
    ],
    cutCriteria: ['Dolor lumbar.', 'Pierde posición.', 'No controla banda.'],
    coachNotes: 'Excelente para curvas y contacto en grupo.',
    skatingSession: false,
    gymSession: true,
    cyclingSession: false,
    recoverySession: false,
    neuralFocused: false,
    metabolicFocused: false,
    reactiveFocused: false,
    technicalFocused: true,
    taperCompatible: true,
    tags: ['core', 'pallof', 'posicion patinaje', 'curva'],
  ),

  TrainingSessionTemplate(
    id: 'core_114',
    number: 114,
    title: 'Extensión lumbar isométrica',
    category: TrainingLibraryCategory.core,
    modality: TrainingLibraryModality.universal,
    intensity: TrainingSessionIntensity.moderate,
    objective: 'Fortalecer erectores espinales para sostener postura baja.',
    type: 'Core posterior',
    warmup: ['Bisagra de cadera.', 'Activación glúteo.'],
    mainSet: ['3-4 x 20-40 seg.', 'Mantener columna neutra.'],
    complementary: ['Movilidad de psoas y respiración.'],
    technicalCues: [
      'Espalda larga.',
      'No hiperextiendas.',
      'Glúteo activo.',
      'Respira.',
    ],
    commonErrors: [
      'Arquear demasiado.',
      'Tensión cervical.',
      'Aguantar aire.',
      'Dolor lumbar.',
    ],
    cutCriteria: [
      'Dolor lumbar agudo.',
      'Hormigueo.',
      'No puede sostener neutro.',
    ],
    coachNotes: 'Debe fortalecer, no irritar la espalda.',
    skatingSession: false,
    gymSession: true,
    cyclingSession: false,
    recoverySession: false,
    neuralFocused: false,
    metabolicFocused: false,
    reactiveFocused: false,
    technicalFocused: true,
    taperCompatible: true,
    tags: ['core', 'lumbar', 'isometrico', 'postura baja'],
  ),

  TrainingSessionTemplate(
    id: 'core_115',
    number: 115,
    title: 'Bird dog técnico',
    category: TrainingLibraryCategory.core,
    modality: TrainingLibraryModality.universal,
    intensity: TrainingSessionIntensity.low,
    objective: 'Mejorar estabilidad lumbo-pélvica y control cruzado.',
    type: 'Core motor',
    warmup: ['Respiración 90/90.', 'Movilidad de columna.'],
    mainSet: ['3 x 8 por lado.', 'Pausa 2 seg extendido.'],
    complementary: ['Dead bug 2 x 8.'],
    technicalCues: [
      'Pelvis quieta.',
      'Alarga brazo y pierna.',
      'No arquees.',
      'Movimiento lento.',
    ],
    commonErrors: [
      'Rotar pelvis.',
      'Elevar pierna demasiado.',
      'Colapsar hombros.',
      'Mover rápido.',
    ],
    cutCriteria: [
      'Dolor lumbar.',
      'No controla pelvis.',
      'Compensación excesiva.',
    ],
    coachNotes: 'Muy bueno para jóvenes y técnica base.',
    skatingSession: false,
    gymSession: true,
    cyclingSession: false,
    recoverySession: false,
    neuralFocused: false,
    metabolicFocused: false,
    reactiveFocused: false,
    technicalFocused: true,
    taperCompatible: true,
    tags: ['core', 'bird dog', 'control motor', 'pelvis'],
  ),

  TrainingSessionTemplate(
    id: 'core_169',
    number: 169,
    title: 'Plancha lateral dinámica',
    category: TrainingLibraryCategory.core,
    modality: TrainingLibraryModality.universal,
    intensity: TrainingSessionIntensity.moderate,
    objective: 'Fortalecer oblicuos y control lateral de pelvis.',
    type: 'Core lateral dinámico',
    warmup: ['Plancha lateral básica.'],
    mainSet: ['3 x 10 elevaciones de cadera por lado.'],
    complementary: ['Copenhagen corto 2 x 20 seg.'],
    technicalCues: [
      'Sube cadera.',
      'No rotes.',
      'Costillas cerradas.',
      'Controla bajada.',
    ],
    commonErrors: [
      'Girar tronco.',
      'Caer de hombro.',
      'Mover rápido.',
      'Tensión cervical.',
    ],
    cutCriteria: ['Dolor lumbar.', 'Dolor hombro.', 'No controla alineación.'],
    coachNotes: 'Muy útil para estabilidad en curva.',
    skatingSession: false,
    gymSession: true,
    cyclingSession: false,
    recoverySession: false,
    neuralFocused: false,
    metabolicFocused: false,
    reactiveFocused: false,
    technicalFocused: true,
    taperCompatible: true,
    tags: ['core', 'lateral', 'dinamico', 'curva'],
  ),

  TrainingSessionTemplate(
    id: 'core_170',
    number: 170,
    title: 'Hollow hold',
    category: TrainingLibraryCategory.core,
    modality: TrainingLibraryModality.universal,
    intensity: TrainingSessionIntensity.moderate,
    objective: 'Mejorar anti-extensión y control del tronco.',
    type: 'Core profundo',
    warmup: ['Dead bug 2 x 8.'],
    mainSet: ['4 x 15-30 seg.', 'Adaptar palancas según nivel.'],
    complementary: ['Respiración 90/90.'],
    technicalCues: [
      'Espalda baja pegada.',
      'Costillas abajo.',
      'Respira corto.',
      'No arquees.',
    ],
    commonErrors: [
      'Lumbar se despega.',
      'Cuello tenso.',
      'Piernas demasiado bajas.',
      'Aguantar aire.',
    ],
    cutCriteria: [
      'Dolor lumbar.',
      'No mantiene posición.',
      'Temblor excesivo.',
    ],
    coachNotes: 'Base para sostener postura fuerte.',
    skatingSession: false,
    gymSession: true,
    cyclingSession: false,
    recoverySession: false,
    neuralFocused: false,
    metabolicFocused: false,
    reactiveFocused: false,
    technicalFocused: true,
    taperCompatible: true,
    tags: ['core', 'hollow', 'anti extension', 'postura'],
  ),
];


