import '../training_library_models.dart';

final List<TrainingSessionTemplate> plyometricSessionsBlock1 = [
  TrainingSessionTemplate(
    id: 'plyometric_013',
    number: 13,
    title: 'Squat jump',
    category: TrainingLibraryCategory.plyometric,
    modality: TrainingLibraryModality.universal,
    intensity: TrainingSessionIntensity.moderate,
    objective: 'Desarrollar fuerza explosiva de miembros inferiores.',
    type: 'Pliometría vertical / potencia',
    warmup: [
      'Movilidad de tobillo, rodilla y cadera.',
      'Activación glúteo-core.',
      '3 series suaves de sentadilla.',
    ],
    mainSet: ['2-4 series x 8-12 repeticiones.', 'Recuperación: 1:30 min.'],
    complementary: ['Estabilidad unilateral 2 x 20 seg.'],
    technicalCues: [
      'Cae suave.',
      'Rodillas alineadas.',
      'Salta vertical con control.',
      'Activa abdomen.',
    ],
    commonErrors: [
      'Valgo de rodilla.',
      'Caer duro.',
      'Perder postura.',
      'Saltar fatigado.',
    ],
    cutCriteria: ['Dolor articular.', 'Caída ruidosa.', 'Pérdida de control.'],
    coachNotes: 'En niños usar bajo impacto y pocas series.',
    skatingSession: false,
    gymSession: true,
    cyclingSession: false,
    recoverySession: false,
    neuralFocused: true,
    metabolicFocused: false,
    reactiveFocused: true,
    technicalFocused: true,
    taperCompatible: false,
    tags: ['pliometria', 'squat jump', 'potencia', 'vertical'],
  ),

  TrainingSessionTemplate(
    id: 'plyometric_014',
    number: 14,
    title: 'Saltos laterales',
    category: TrainingLibraryCategory.plyometric,
    modality: TrainingLibraryModality.universal,
    intensity: TrainingSessionIntensity.moderate,
    objective: 'Mejorar potencia lateral específica del empuje.',
    type: 'Pliometría lateral',
    warmup: [
      'Movilidad de cadera.',
      'Saltos suaves en el sitio.',
      'Activación glúteo medio.',
    ],
    mainSet: ['3 x 20-35 seg.', 'Recuperación: 1:30-2 min.'],
    complementary: ['2 x 8 empujes laterales lentos.'],
    technicalCues: [
      'Empuja el suelo.',
      'Cae estable.',
      'Cadera baja.',
      'No colapses rodilla.',
    ],
    commonErrors: [
      'Saltar hacia arriba.',
      'Caer sin control.',
      'Rodilla hacia adentro.',
      'Tronco desalineado.',
    ],
    cutCriteria: [
      'Pierde estabilidad.',
      'Dolor de rodilla.',
      'Fatiga excesiva.',
    ],
    coachNotes: 'Transferencia directa al empuje lateral.',
    skatingSession: false,
    gymSession: true,
    cyclingSession: false,
    recoverySession: false,
    neuralFocused: true,
    metabolicFocused: false,
    reactiveFocused: true,
    technicalFocused: true,
    taperCompatible: false,
    tags: ['pliometria', 'lateral', 'empuje', 'potencia'],
  ),

  TrainingSessionTemplate(
    id: 'plyometric_015',
    number: 15,
    title: 'Saltos de curva',
    category: TrainingLibraryCategory.plyometric,
    modality: TrainingLibraryModality.universal,
    intensity: TrainingSessionIntensity.moderate,
    objective: 'Mejorar potencia, rotación controlada y estabilidad en curva.',
    type: 'Pliometría específica de curva',
    warmup: [
      'Movilidad de cadera.',
      'Activación core-oblicuos.',
      'Saltos laterales suaves.',
    ],
    mainSet: ['3 x 20-30 seg.', 'Recuperación: 1:30 min.'],
    complementary: ['3 curvas técnicas en patines.'],
    technicalCues: [
      'Rota poco, controla mucho.',
      'Cadera entra primero.',
      'Cae estable.',
      'Rodilla sigue la línea del pie.',
    ],
    commonErrors: [
      'Rotar demasiado.',
      'Caer rígido.',
      'Perder cadera.',
      'Usar solo tobillo.',
    ],
    cutCriteria: [
      'Pierde control en la caída.',
      'Dolor lumbar.',
      'Rodilla inestable.',
    ],
    coachNotes: 'Muy útil antes de sesiones de curva.',
    skatingSession: false,
    gymSession: true,
    cyclingSession: false,
    recoverySession: false,
    neuralFocused: true,
    metabolicFocused: false,
    reactiveFocused: true,
    technicalFocused: true,
    taperCompatible: false,
    tags: ['pliometria', 'curva', 'rotacion', 'lateral'],
  ),

  TrainingSessionTemplate(
    id: 'plyometric_016',
    number: 16,
    title: 'Saltos a una pierna',
    category: TrainingLibraryCategory.plyometric,
    modality: TrainingLibraryModality.universal,
    intensity: TrainingSessionIntensity.high,
    objective: 'Mejorar estabilidad, stiffness y potencia unilateral.',
    type: 'Pliometría unilateral',
    warmup: [
      'Equilibrio unilateral.',
      'Movilidad de tobillo.',
      'Activación glúteo medio.',
    ],
    mainSet: [
      '2-3 series x 8-12 saltos por pierna.',
      'Recuperación: 1:30-2 min.',
    ],
    complementary: ['2 x 20 seg equilibrio en una pierna.'],
    technicalCues: [
      'Cae silencioso.',
      'Rodilla estable.',
      'Pie activo.',
      'Cadera firme.',
    ],
    commonErrors: [
      'Rodilla hacia adentro.',
      'Caer con talón pesado.',
      'Balanceo excesivo de brazos.',
      'Perder postura.',
    ],
    cutCriteria: [
      'Hay inestabilidad marcada.',
      'Dolor de tobillo o rodilla.',
      'Caída ruidosa.',
    ],
    coachNotes: 'No usar con fatiga alta.',
    skatingSession: false,
    gymSession: true,
    cyclingSession: false,
    recoverySession: false,
    neuralFocused: true,
    metabolicFocused: false,
    reactiveFocused: true,
    technicalFocused: true,
    taperCompatible: false,
    tags: ['pliometria', 'unilateral', 'stiffness', 'potencia'],
  ),
];


