// lib/training_library/recovery/recovery_sessions_block_1.dart

import '../training_library_models.dart';

final List<TrainingSessionTemplate> recoverySessionsBlock1 = [
  TrainingSessionTemplate(
    id: 'recovery_048',
    number: 48,
    title: 'Movilidad psoas-ilíaco',
    category: TrainingLibraryCategory.mobility,
    modality: TrainingLibraryModality.universal,
    intensity: TrainingSessionIntensity.recovery,
    objective:
        'Liberar tensión anterior de cadera y mejorar extensión para la postura baja del patinaje.',
    type: 'Movilidad / descarga',
    warmup: [
      'Respiración nasal 2 minutos.',
      'Balanceo suave de cadera 2 x 10 por lado.',
      'Movilidad de columna en cuadrupedia 2 x 8.',
    ],
    mainSet: [
      'Estiramiento de psoas en medio arrodillado 3 x 40 segundos por lado.',
      'Psoas con brazo arriba y ligera inclinación lateral 2 x 30 segundos por lado.',
      'Activación de glúteo posterior 2 x 12 por lado.',
    ],
    complementary: [
      'Caminata suave 5 minutos.',
      'Respiración 90/90 3 minutos.',
    ],
    technicalCues: [
      'Retroversión pélvica suave.',
      'No arquear la zona lumbar.',
      'Mantener respiración lenta.',
    ],
    commonErrors: [
      'Compensar con hiperextensión lumbar.',
      'Forzar el rango con dolor.',
      'Perder alineación de cadera y rodilla.',
    ],
    cutCriteria: [
      'Dolor punzante en cadera o lumbar.',
      'Hormigueo o sensación nerviosa.',
      'Aumento de rigidez después de cada repetición.',
    ],
    coachNotes:
        'Ideal después de sesiones de postura baja, curvas o gimnasio de pierna.',
    skatingSession: false,
    gymSession: false,
    cyclingSession: false,
    recoverySession: true,
    neuralFocused: false,
    metabolicFocused: false,
    reactiveFocused: false,
    technicalFocused: true,
    taperCompatible: true,
    tags: ['recovery', 'mobility', 'psoas', 'hip', 'posture'],
  ),
  TrainingSessionTemplate(
    id: 'recovery_049',
    number: 49,
    title: 'Liberación tibial y pie',
    category: TrainingLibraryCategory.recovery,
    modality: TrainingLibraryModality.universal,
    intensity: TrainingSessionIntensity.recovery,
    objective:
        'Reducir carga distal en tibial, pie y tobillo después de trabajo técnico o volumen en patines.',
    type: 'Liberación / descarga distal',
    warmup: [
      'Caminata suave 3 minutos.',
      'Círculos de tobillo 2 x 10 por lado.',
      'Flexión y extensión de dedos 2 x 12.',
    ],
    mainSet: [
      'Automasaje en tibial anterior 2 x 60 segundos por pierna.',
      'Liberación de planta del pie con pelota 2 x 60 segundos por pie.',
      'Movilidad de tobillo suave 2 x 12 por lado.',
    ],
    complementary: [
      'Elevaciones suaves de dedos 2 x 15.',
      'Respiración nasal 2 minutos.',
    ],
    technicalCues: [
      'Presión tolerable, no agresiva.',
      'Mover lento.',
      'Buscar sensación de descarga, no dolor.',
    ],
    commonErrors: [
      'Presionar demasiado fuerte.',
      'Trabajar sobre dolor agudo.',
      'Hacerlo rápido y sin control.',
    ],
    cutCriteria: [
      'Dolor agudo en tibia.',
      'Inflamación visible.',
      'Molestia que aumenta al caminar.',
    ],
    coachNotes:
        '�stil para proteger tobillo, tibial y pie en bloques con mucha técnica, curvas o volumen.',
    skatingSession: false,
    gymSession: false,
    cyclingSession: false,
    recoverySession: true,
    neuralFocused: false,
    metabolicFocused: false,
    reactiveFocused: false,
    technicalFocused: false,
    taperCompatible: true,
    tags: ['recovery', 'foot', 'tibial', 'ankle', 'distal-load'],
  ),
  TrainingSessionTemplate(
    id: 'recovery_070',
    number: 70,
    title: 'Respiración 90/90',
    category: TrainingLibraryCategory.recovery,
    modality: TrainingLibraryModality.universal,
    intensity: TrainingSessionIntensity.recovery,
    objective:
        'Bajar activación del sistema nervioso y favorecer recuperación autonómica.',
    type: 'Respiración / regulación',
    warmup: [
      'Acostarse en posición cómoda.',
      'Pies apoyados en pared o banco.',
      'Relajar cuello y hombros.',
    ],
    mainSet: [
      'Respiración 90/90: 5 bloques de 6 respiraciones lentas.',
      'Exhalación larga de 5 a 7 segundos.',
      'Pausa suave después de exhalar 2 segundos.',
    ],
    complementary: [
      'Movilidad torácica suave 2 x 6 por lado.',
      'Caminata ligera 5 minutos si hay rigidez.',
    ],
    technicalCues: [
      'Costillas abajo.',
      'Inhalar por nariz.',
      'Exhalar lento sin tensión.',
    ],
    commonErrors: [
      'Elevar hombros al inhalar.',
      'Forzar la apnea.',
      'Arquear la espalda baja.',
    ],
    cutCriteria: [
      'Mareo persistente.',
      'Sensación de falta de aire.',
      'Ansiedad o incomodidad creciente.',
    ],
    coachNotes:
        'Muy compatible con días rojos, taper, post-competencia y sesiones nocturnas.',
    skatingSession: false,
    gymSession: false,
    cyclingSession: false,
    recoverySession: true,
    neuralFocused: false,
    metabolicFocused: false,
    reactiveFocused: false,
    technicalFocused: false,
    taperCompatible: true,
    tags: ['recovery', 'breathing', '90-90', 'parasympathetic', 'sleep'],
  ),
  TrainingSessionTemplate(
    id: 'recovery_071',
    number: 71,
    title: 'Rodaje muy suave + movilidad',
    category: TrainingLibraryCategory.recovery,
    modality: TrainingLibraryModality.universal,
    intensity: TrainingSessionIntensity.recovery,
    objective:
        'Facilitar recuperación activa sin acumular carga metabólica ni neuromuscular.',
    type: 'Patines regenerativo',
    warmup: [
      'Movilidad articular general 5 minutos.',
      'Rodaje muy suave 8 minutos.',
      'Técnica simple de postura relajada.',
    ],
    mainSet: [
      'Rodaje Z1 de 20 a 30 minutos.',
      'Cada 6 minutos incluir 1 minuto de técnica suave.',
      'Mantener sensación de facilidad durante toda la sesión.',
    ],
    complementary: [
      'Movilidad de cadera 5 minutos.',
      'Movilidad de tobillo 3 minutos.',
      'Respiración 90/90 3 minutos.',
    ],
    technicalCues: [
      'Patinar fácil.',
      'No perseguir velocidad.',
      'Empuje limpio y relajado.',
    ],
    commonErrors: [
      'Convertirlo en tempo.',
      'Acelerar por sensaciones buenas.',
      'Mantener postura baja demasiado tiempo.',
    ],
    cutCriteria: [
      'Piernas pesadas que empeoran.',
      'Pulso sube fuera de Z1/Z2.',
      'Dolor articular o tendinoso.',
    ],
    coachNotes:
        'Debe dejar al atleta mejor que antes de empezar. Si no, cambiar por movilidad sin patines.',
    skatingSession: true,
    gymSession: false,
    cyclingSession: false,
    recoverySession: true,
    neuralFocused: false,
    metabolicFocused: false,
    reactiveFocused: false,
    technicalFocused: true,
    taperCompatible: true,
    tags: ['recovery', 'skating', 'z1', 'mobility', 'easy'],
  ),
  TrainingSessionTemplate(
    id: 'recovery_096',
    number: 96,
    title: 'Movilidad de tobillo con rodilla a pared',
    category: TrainingLibraryCategory.mobility,
    modality: TrainingLibraryModality.universal,
    intensity: TrainingSessionIntensity.recovery,
    objective:
        'Mejorar dorsiflexión de tobillo y reducir compensaciones en técnica de patinaje.',
    type: 'Movilidad de tobillo',
    warmup: [
      'Caminata suave 3 minutos.',
      'Círculos de tobillo 2 x 10 por lado.',
      'Elevaciones de talón suaves 2 x 12.',
    ],
    mainSet: [
      'Rodilla a pared 3 x 10 por lado.',
      'Rodilla a pared con pausa final 2 x 20 segundos por lado.',
      'Dorsiflexión controlada en apoyo 2 x 8 por lado.',
    ],
    complementary: [
      'Sóleo isométrico suave 2 x 20 segundos por lado.',
      'Liberación de planta del pie 1 minuto por lado.',
    ],
    technicalCues: [
      'Talón siempre apoyado.',
      'Rodilla sigue línea del segundo dedo.',
      'Movimiento lento y sin rebote.',
    ],
    commonErrors: [
      'Levantar el talón.',
      'Colapsar el arco del pie.',
      'Forzar dolor anterior de tobillo.',
    ],
    cutCriteria: [
      'Pinzamiento fuerte anterior.',
      'Dolor en Aquiles.',
      'Pérdida de control del arco plantar.',
    ],
    coachNotes:
        'Buena sesión corta antes o después de técnica, especialmente si hay rigidez de tobillo.',
    skatingSession: false,
    gymSession: false,
    cyclingSession: false,
    recoverySession: true,
    neuralFocused: false,
    metabolicFocused: false,
    reactiveFocused: false,
    technicalFocused: true,
    taperCompatible: true,
    tags: ['mobility', 'ankle', 'dorsiflexion', 'recovery', 'technique'],
  ),
  TrainingSessionTemplate(
    id: 'recovery_097',
    number: 97,
    title: 'Movilidad torácica en rotación',
    category: TrainingLibraryCategory.mobility,
    modality: TrainingLibraryModality.universal,
    intensity: TrainingSessionIntensity.recovery,
    objective:
        'Mejorar rotación torácica y liberar tensión de tronco para postura eficiente.',
    type: 'Movilidad torácica',
    warmup: [
      'Respiración costal 2 minutos.',
      'Cat-camel 2 x 8.',
      'Rotaciones suaves de hombro 2 x 10.',
    ],
    mainSet: [
      'Open book 3 x 8 por lado.',
      'Rotación torácica en cuadrupedia 3 x 8 por lado.',
      'Thread the needle 2 x 8 por lado.',
    ],
    complementary: [
      'Estiramiento de dorsal 2 x 30 segundos.',
      'Respiración 90/90 3 minutos.',
    ],
    technicalCues: [
      'Rotar desde la espalda alta.',
      'Mantener cadera estable.',
      'No forzar cuello.',
    ],
    commonErrors: [
      'Compensar desde lumbar.',
      'Mover rápido.',
      'Bloquear respiración.',
    ],
    cutCriteria: [
      'Dolor cervical.',
      'Dolor lumbar.',
      'Mareo o incomodidad respiratoria.',
    ],
    coachNotes:
        '�stil para atletas con rigidez por postura baja prolongada o gimnasio.',
    skatingSession: false,
    gymSession: false,
    cyclingSession: false,
    recoverySession: true,
    neuralFocused: false,
    metabolicFocused: false,
    reactiveFocused: false,
    technicalFocused: true,
    taperCompatible: true,
    tags: ['mobility', 'thoracic', 'rotation', 'posture', 'recovery'],
  ),
  TrainingSessionTemplate(
    id: 'recovery_122',
    number: 122,
    title: 'Estiramiento de isquios activo',
    category: TrainingLibraryCategory.mobility,
    modality: TrainingLibraryModality.universal,
    intensity: TrainingSessionIntensity.low,
    objective:
        'Mejorar movilidad posterior sin inhibir fuerza ni generar fatiga residual.',
    type: 'Movilidad activa',
    warmup: [
      'Bisagra de cadera sin carga 2 x 10.',
      'Movilidad de tobillo 2 x 8.',
      'Activación de glúteo 2 x 10.',
    ],
    mainSet: [
      'Elevación activa de pierna 3 x 8 por lado.',
      'Isquios con banda en rango cómodo 3 x 30 segundos por lado.',
      'Buenos días sin carga 2 x 10.',
    ],
    complementary: ['Puente de glúteo 2 x 12.', 'Respiración nasal 2 minutos.'],
    technicalCues: [
      'Buscar tensión tolerable.',
      'Mantener pelvis estable.',
      'No bloquear rodilla agresivamente.',
    ],
    commonErrors: [
      'Redondear lumbar.',
      'Forzar rango pasivo.',
      'Convertirlo en ejercicio de fuerza.',
    ],
    cutCriteria: [
      'Dolor tipo tirón.',
      'Sensación nerviosa detrás de rodilla.',
      'Aumento de rigidez posterior.',
    ],
    coachNotes:
        'Usar como descarga posterior después de fondo, gimnasio o días con mucha postura baja.',
    skatingSession: false,
    gymSession: false,
    cyclingSession: false,
    recoverySession: true,
    neuralFocused: false,
    metabolicFocused: false,
    reactiveFocused: false,
    technicalFocused: true,
    taperCompatible: true,
    tags: ['mobility', 'hamstrings', 'posterior-chain', 'recovery'],
  ),
  TrainingSessionTemplate(
    id: 'recovery_123',
    number: 123,
    title: 'Movilidad de cuadrado lumbar',
    category: TrainingLibraryCategory.mobility,
    modality: TrainingLibraryModality.universal,
    intensity: TrainingSessionIntensity.recovery,
    objective: 'Reducir tensión lumbar lateral y mejorar control de pelvis.',
    type: 'Movilidad lumbar suave',
    warmup: [
      'Respiración diafragmática 2 minutos.',
      'Cat-camel 2 x 8.',
      'Balanceo de cadera 2 x 10.',
    ],
    mainSet: [
      'Estiramiento lateral en posición de niño 3 x 30 segundos por lado.',
      'Inclinación lateral de pelvis en suelo 2 x 10 por lado.',
      'Rotación lumbar suave 2 x 8 por lado.',
    ],
    complementary: [
      'Bird dog suave 2 x 8 por lado.',
      'Respiración 90/90 3 minutos.',
    ],
    technicalCues: [
      'Movimiento lento.',
      'No buscar dolor.',
      'Mantener respiración continua.',
    ],
    commonErrors: [
      'Forzar rotación lumbar.',
      'Perder control de pelvis.',
      'Aguantar la respiración.',
    ],
    cutCriteria: [
      'Dolor irradiado.',
      'Dolor lumbar agudo.',
      'Espasmo o bloqueo.',
    ],
    coachNotes:
        'Especialmente útil después de curvas, traspiés, gimnasio unilateral o mucho volumen técnico.',
    skatingSession: false,
    gymSession: false,
    cyclingSession: false,
    recoverySession: true,
    neuralFocused: false,
    metabolicFocused: false,
    reactiveFocused: false,
    technicalFocused: true,
    taperCompatible: true,
    tags: ['mobility', 'lumbar', 'ql', 'pelvis', 'recovery'],
  ),
  TrainingSessionTemplate(
    id: 'recovery_148',
    number: 148,
    title: 'Liberación de psoas indirecta',
    category: TrainingLibraryCategory.recovery,
    modality: TrainingLibraryModality.universal,
    intensity: TrainingSessionIntensity.recovery,
    objective:
        'Disminuir tono de flexores de cadera sin presión directa agresiva.',
    type: 'Liberación indirecta',
    warmup: [
      'Respiración 90/90 3 minutos.',
      'Balanceo suave de rodillas 2 x 10.',
      'Movilidad pélvica 2 x 8.',
    ],
    mainSet: [
      'Posición 90/90 con pies elevados 4 minutos.',
      'Exhalaciones largas con costillas abajo 5 x 5 respiraciones.',
      'Activación suave de glúteo 2 x 10 por lado.',
    ],
    complementary: [
      'Estiramiento suave de flexor de cadera 2 x 25 segundos por lado.',
      'Caminata relajada 5 minutos.',
    ],
    technicalCues: [
      'No presionar profundo el abdomen.',
      'Relajar mandíbula y hombros.',
      'Sentir descarga anterior de cadera.',
    ],
    commonErrors: [
      'Buscar dolor profundo.',
      'Arquear lumbar.',
      'Hacer activaciones fuertes.',
    ],
    cutCriteria: [
      'Dolor abdominal o lumbar.',
      'Hormigueo hacia pierna.',
      'Molestia que aumenta al ponerse de pie.',
    ],
    coachNotes:
        'Preferible a liberaciones agresivas cuando el atleta está muy cargado o cerca de competencia.',
    skatingSession: false,
    gymSession: false,
    cyclingSession: false,
    recoverySession: true,
    neuralFocused: false,
    metabolicFocused: false,
    reactiveFocused: false,
    technicalFocused: false,
    taperCompatible: true,
    tags: ['recovery', 'psoas', 'breathing', 'hip', 'taper'],
  ),
  TrainingSessionTemplate(
    id: 'recovery_149',
    number: 149,
    title: 'Descarga de isquios y glúteos',
    category: TrainingLibraryCategory.recovery,
    modality: TrainingLibraryModality.universal,
    intensity: TrainingSessionIntensity.recovery,
    objective:
        'Reducir tensión posterior y mejorar sensación de piernas después de carga de fuerza o patines.',
    type: 'Descarga posterior',
    warmup: [
      'Caminata suave 5 minutos.',
      'Puente de glúteo suave 2 x 10.',
      'Bisagra sin carga 2 x 8.',
    ],
    mainSet: [
      'Liberación de glúteo con pelota 2 x 60 segundos por lado.',
      'Isquios con banda en rango cómodo 2 x 40 segundos por lado.',
      'Rockback de cadera 2 x 10.',
    ],
    complementary: [
      'Respiración 90/90 3 minutos.',
      'Movilidad lumbar suave 2 x 8.',
    ],
    technicalCues: [
      'Presión moderada.',
      'Evitar dolor nervioso.',
      'Respirar lento durante la descarga.',
    ],
    commonErrors: [
      'Presionar sobre ciático.',
      'Forzar estiramiento posterior.',
      'Salir con sensación de debilidad.',
    ],
    cutCriteria: [
      'Dolor irradiado.',
      'Calambre persistente.',
      'Aumento de tensión posterior.',
    ],
    coachNotes:
        'Buena opción después de peso muerto, sentadilla, fondo largo o lactato.',
    skatingSession: false,
    gymSession: false,
    cyclingSession: false,
    recoverySession: true,
    neuralFocused: false,
    metabolicFocused: false,
    reactiveFocused: false,
    technicalFocused: false,
    taperCompatible: true,
    tags: ['recovery', 'hamstrings', 'glutes', 'posterior-chain'],
  ),
  TrainingSessionTemplate(
    id: 'recovery_173',
    number: 173,
    title: 'Movilidad global post-entreno',
    category: TrainingLibraryCategory.recovery,
    modality: TrainingLibraryModality.universal,
    intensity: TrainingSessionIntensity.recovery,
    objective:
        'Cerrar la sesión reduciendo rigidez, recuperando rango y bajando activación.',
    type: 'Post-entreno / movilidad global',
    warmup: ['Caminata suave 3 minutos.', 'Respiración nasal 1 minuto.'],
    mainSet: [
      'Movilidad de tobillo 2 x 8 por lado.',
      'Flexor de cadera 2 x 30 segundos por lado.',
      'Rotación torácica 2 x 8 por lado.',
      'Isquios activo 2 x 8 por lado.',
      'Posición de niño con respiración 2 minutos.',
    ],
    complementary: [
      'Respiración 90/90 3 minutos.',
      'Hidratación y descarga fuera de pantalla 10 minutos.',
    ],
    technicalCues: [
      'Bajar revoluciones.',
      'Mover sin dolor.',
      'Respirar lento.',
    ],
    commonErrors: [
      'Hacer movilidad como entrenamiento intenso.',
      'Rebotar en los estiramientos.',
      'Saltarse la respiración final.',
    ],
    cutCriteria: [
      'Dolor articular.',
      'Mareo.',
      'Sensación de fatiga que empeora.',
    ],
    coachNotes:
        'Puede usarse casi todos los días al terminar, especialmente en semanas de alta carga.',
    skatingSession: false,
    gymSession: false,
    cyclingSession: false,
    recoverySession: true,
    neuralFocused: false,
    metabolicFocused: false,
    reactiveFocused: false,
    technicalFocused: true,
    taperCompatible: true,
    tags: ['recovery', 'mobility', 'post-training', 'global'],
  ),
  TrainingSessionTemplate(
    id: 'recovery_174',
    number: 174,
    title: 'Descarga activa en patines 20 minutos',
    category: TrainingLibraryCategory.recovery,
    modality: TrainingLibraryModality.universal,
    intensity: TrainingSessionIntensity.recovery,
    objective:
        'Promover recuperación activa específica en patines sin generar fatiga.',
    type: 'Patines regenerativo corto',
    warmup: ['Movilidad general 5 minutos.', 'Rodaje muy suave 5 minutos.'],
    mainSet: [
      'Rodaje Z1 continuo 20 minutos.',
      'Mantener técnica relajada y respiración controlada.',
      'No incluir sprints, cambios de ritmo ni persecuciones.',
    ],
    complementary: [
      'Movilidad de cadera 4 minutos.',
      'Movilidad de tobillo 3 minutos.',
      'Respiración 90/90 3 minutos.',
    ],
    technicalCues: [
      'Patín silencioso.',
      'Empuje suave.',
      'Postura cómoda, no extrema.',
    ],
    commonErrors: [
      'Subir intensidad por grupo.',
      'Rodar demasiado tiempo.',
      'Forzar postura baja.',
    ],
    cutCriteria: [
      'Pulso fuera de Z1/Z2.',
      'Dolor en tobillo, rodilla o lumbar.',
      'Sensación de piernas más pesadas.',
    ],
    coachNotes:
        'Excelente para día posterior a competencia, lactato o gimnasio fuerte. Debe sentirse regenerativo.',
    skatingSession: true,
    gymSession: false,
    cyclingSession: false,
    recoverySession: true,
    neuralFocused: false,
    metabolicFocused: false,
    reactiveFocused: false,
    technicalFocused: true,
    taperCompatible: true,
    tags: ['recovery', 'skating', 'active-recovery', 'z1', 'taper'],
  ),
];


