import '../training_library_models.dart';

final List<TrainingSessionTemplate> raceSimulationSessionsBlock1 = [
  TrainingSessionTemplate(
    id: 'simulation_072',
    number: 72,
    title: 'Simulación 500 m',
    category: TrainingLibraryCategory.tactical,
    modality: TrainingLibraryModality.sprinter,
    intensity: TrainingSessionIntensity.maximal,
    objective:
        'Simular un 500 m competitivo trabajando salida, aceleración, curva y cierre.',
    type: 'Simulación competitiva',
    warmup: [
      'Rodaje suave 12 minutos.',
      'Movilidad dinámica 5 minutos.',
      '3 progresivos de 100 m.',
      '2 salidas cortas de 20 m.',
    ],
    mainSet: [
      '1 a 3 simulaciones de 500 m.',
      'Recuperación completa 10 a 15 minutos.',
      'Registrar tiempo, parciales y percepción.',
    ],
    complementary: [
      'Rodaje suave 10 minutos.',
      'Movilidad de cadera, aductores y tobillo.',
    ],
    technicalCues: [
      'Salida agresiva pero limpia.',
      'No romper técnica en la curva.',
      'Cierre fuerte sin perder postura.',
    ],
    commonErrors: [
      'Salir demasiado tenso.',
      'Perder frecuencia en la curva.',
      'Desarmarse en los últimos 100 m.',
    ],
    cutCriteria: [
      'Caída clara de técnica.',
      'Dolor muscular o articular.',
      'Pérdida mayor al 5% entre repeticiones.',
    ],
    coachNotes:
        'Sesión de alta carga neural y metabólica. No programar con readiness bajo.',
    skatingSession: true,
    gymSession: false,
    cyclingSession: false,
    recoverySession: false,
    neuralFocused: true,
    metabolicFocused: true,
    reactiveFocused: true,
    technicalFocused: true,
    taperCompatible: false,
    tags: ['simulation', '500m', 'sprinter', 'race-pace', 'lactate'],
  ),
  TrainingSessionTemplate(
    id: 'simulation_073',
    number: 73,
    title: 'Simulación 1000 m con remate',
    category: TrainingLibraryCategory.tactical,
    modality: TrainingLibraryModality.mixed,
    intensity: TrainingSessionIntensity.high,
    objective: 'Simular un 1000 m controlando ritmo, ubicación y remate final.',
    type: 'Simulación competitiva',
    warmup: [
      'Rodaje suave 15 minutos.',
      'Movilidad dinámica.',
      '3 progresivos de 100 m.',
      '1 aceleración de 200 m controlada.',
    ],
    mainSet: [
      '1 a 2 simulaciones de 1000 m.',
      '�sltimos 200 m con remate.',
      'Recuperación completa 12 a 18 minutos.',
    ],
    complementary: [
      'Rodaje suave 10 minutos.',
      'Respiración 90/90 3 minutos.',
      'Movilidad global.',
    ],
    technicalCues: [
      'No gastar todo en la primera mitad.',
      'Mantener postura baja eficiente.',
      'Rematar con técnica, no solo fuerza.',
    ],
    commonErrors: [
      'Salir como 500 m.',
      'Llegar sin piernas al remate.',
      'Perder línea por fatiga.',
    ],
    cutCriteria: [
      'Técnica degradada.',
      'Exceso de lactato temprano.',
      'Dolor o pérdida de control.',
    ],
    coachNotes:
        'Muy útil para velocistas largos y mixtos. Controlar fatiga posterior.',
    skatingSession: true,
    gymSession: false,
    cyclingSession: false,
    recoverySession: false,
    neuralFocused: true,
    metabolicFocused: true,
    reactiveFocused: false,
    technicalFocused: true,
    taperCompatible: false,
    tags: ['simulation', '1000m', 'finish', 'race-pace', 'mixed'],
  ),
  TrainingSessionTemplate(
    id: 'simulation_074',
    number: 74,
    title: 'Simulación puntos',
    category: TrainingLibraryCategory.tactical,
    modality: TrainingLibraryModality.endurance,
    intensity: TrainingSessionIntensity.high,
    objective:
        'Simular carrera por puntos trabajando ubicación, metas volantes, ataques y recuperación.',
    type: 'Simulación táctica en grupo',
    warmup: [
      'Rodaje grupal suave 15 minutos.',
      'Relevos suaves 5 minutos.',
      '3 aceleraciones progresivas.',
    ],
    mainSet: [
      'Simulación de carrera por puntos de 12 a 20 vueltas.',
      'Meta volante cada 3 o 4 vueltas.',
      'Alternar roles: atacar, perseguir, guardar rueda y rematar.',
    ],
    complementary: [
      'Rodaje suave 10 minutos.',
      'Movilidad de aductores, cadera y psoas.',
    ],
    technicalCues: [
      'Ganar posición antes de la meta.',
      'No atacar desde demasiado lejos.',
      'Recuperar en drafting después del esfuerzo.',
    ],
    commonErrors: [
      'Gastar energía sin posición.',
      'Cerrar líneas peligrosas.',
      'Responder a todos los ataques sin criterio.',
    ],
    cutCriteria: [
      'Grupo inseguro.',
      'Fatiga que degrade técnica.',
      'Exceso de contacto o riesgo de caída.',
    ],
    coachNotes:
        'Alta carga táctica y metabólica. Ideal para fondistas y mixtos.',
    skatingSession: true,
    gymSession: false,
    cyclingSession: false,
    recoverySession: false,
    neuralFocused: true,
    metabolicFocused: true,
    reactiveFocused: false,
    technicalFocused: true,
    taperCompatible: false,
    tags: ['simulation', 'points-race', 'tactical', 'group', 'metas-volantes'],
  ),
  TrainingSessionTemplate(
    id: 'simulation_075',
    number: 75,
    title: 'Simulación eliminación',
    category: TrainingLibraryCategory.tactical,
    modality: TrainingLibraryModality.endurance,
    intensity: TrainingSessionIntensity.high,
    objective:
        'Simular carrera de eliminación trabajando ubicación, aceleración corta y toma de decisiones.',
    type: 'Simulación táctica en grupo',
    warmup: [
      'Rodaje grupal suave 15 minutos.',
      'Práctica de cambios de posición 5 minutos.',
      '3 aceleraciones cortas.',
    ],
    mainSet: [
      'Simulación de eliminación de 12 a 20 vueltas.',
      'Eliminación cada 2 vueltas.',
      'Practicar sobrevivir sin gastar energía innecesaria.',
    ],
    complementary: [
      'Rodaje suave 10 minutos.',
      'Movilidad global post-entreno.',
    ],
    technicalCues: [
      'Anticipar la vuelta de eliminación.',
      'No quedar encerrado.',
      'Acelerar antes de estar en peligro.',
    ],
    commonErrors: [
      'Esperar demasiado para moverse.',
      'Ir siempre por fuera gastando energía.',
      'Cambiar de línea sin mirar.',
    ],
    cutCriteria: [
      'Grupo inseguro.',
      'Fatiga excesiva.',
      'Pérdida de técnica en aceleraciones.',
    ],
    coachNotes:
        'Sesión clave para toma de decisiones. Alta exigencia mental y metabólica.',
    skatingSession: true,
    gymSession: false,
    cyclingSession: false,
    recoverySession: false,
    neuralFocused: true,
    metabolicFocused: true,
    reactiveFocused: false,
    technicalFocused: true,
    taperCompatible: false,
    tags: ['simulation', 'elimination', 'tactical', 'group', 'positioning'],
  ),
];


